// Generated from data/researched-recipes.mjs by npm run build.
import Foundation

enum CuratedCocktailData {
    static let recipes: [CocktailRecipe] = [
        CocktailRecipe(
            id: "iba-paper-plane",
            englishName: "Paper Plane",
            chineseName: "纸飞机",
            ingredients: ["波本 30 ml", "Amaro Nonino 30 ml", "阿佩罗 30 ml", "柠檬汁 30 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。不需装饰。",
            note: nil,
            accentHex: "#df9751",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-last-word",
            englishName: "Last Word",
            chineseName: "最后一语",
            ingredients: ["金酒 22.5 ml", "绿查特酒 22.5 ml", "马拉斯奇诺 22.5 ml", "青柠汁 22.5 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。不需装饰。",
            note: nil,
            accentHex: "#c8d38e",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-french-martini",
            englishName: "French Martini",
            chineseName: "法式马天尼",
            ingredients: ["伏特加 45 ml", "覆盆子利口酒 15 ml", "菠萝汁 15 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。在表面挤出柠檬皮油。",
            note: nil,
            accentHex: "#d394a1",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-grasshopper",
            englishName: "Grasshopper",
            chineseName: "蚱蜢",
            ingredients: ["白可可利口酒 20 ml", "绿薄荷利口酒 20 ml", "奶油 20 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，短暂摇匀后过滤入预冷的鸡尾酒杯。可用薄荷叶装饰。",
            note: nil,
            accentHex: "#a9d3a6",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-hemingway-special",
            englishName: "Hemingway Special",
            chineseName: "海明威特调",
            ingredients: ["朗姆 60 ml", "西柚汁 40 ml", "马拉斯奇诺 15 ml", "青柠汁 15 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，摇匀后过滤入预冷的大号鸡尾酒杯。不需装饰。",
            note: nil,
            accentHex: "#eed2b8",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-corpse-reviver-2",
            englishName: "Corpse Reviver #2",
            chineseName: "亡者复苏二号",
            ingredients: ["金酒 30 ml", "君度 30 ml", "Lillet Blanc 30 ml", "柠檬汁 30 ml", "苦艾酒 1 dash"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。用橙皮装饰。",
            note: nil,
            accentHex: "#e4dba4",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-gin-basil-smash",
            englishName: "Gin Basil Smash",
            chineseName: "金酒罗勒司马什",
            ingredients: ["金酒 60 ml", "柠檬汁 22.5 ml", "糖浆 22.5 ml", "罗勒 10 片"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "材料与冰块加入摇壶，用力摇匀后过滤入预冷的鸡尾酒杯。不需装饰。",
            note: nil,
            accentHex: "#99b664",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-dark-n-stormy",
            englishName: "Dark ’N’ Stormy",
            chineseName: "黑暗风暴",
            ingredients: ["黑朗姆 60 ml", "姜汁啤酒 100 ml"],
            tags: ["IBA 精选", "分层"],
            glass: "高球杯",
            method: "高球杯装满冰，先倒入姜汁啤酒，再将 Goslings 朗姆漂浮在上层。用青柠角或片装饰。",
            note: "IBA 指定 Goslings 朗姆；使用其他黑朗姆时是家庭替代版本。",
            accentHex: "#ead4a0",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-garibaldi",
            englishName: "Garibaldi",
            chineseName: "加里波第",
            ingredients: ["金巴利 45 ml", "橙汁 120 ml"],
            tags: ["IBA 精选", "直接调和"],
            glass: "高球杯",
            method: "在高球杯中加冰，加入金巴利和橙汁，轻轻调和，以橙角装饰。",
            note: nil,
            accentHex: "#ec793f",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-brandy-crusta",
            englishName: "Brandy Crusta",
            chineseName: "白兰地克鲁斯塔",
            ingredients: ["白兰地 52.5 ml", "马拉斯奇诺 7.5 ml", "橙味利口酒 1 吧勺", "柠檬汁 15 ml", "糖浆 1 吧勺", "苦精 2 dash"],
            tags: ["IBA 精选", "搅拌"],
            glass: "细长鸡尾酒杯",
            method: "用柠檬或橙润湿杯缘，蘸细砂糖，放入一条卷起的长柑橘皮。将其余材料在调酒杯中加冰搅匀，过滤入准备好的杯子。",
            note: "来源中的吧勺与 dash 保留原单位；糖边和长柑橘皮另外准备。",
            accentHex: "#d4ad62",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-angel-face",
            englishName: "Angel Face",
            chineseName: "天使之面",
            ingredients: ["金酒 30 ml", "杏子白兰地 30 ml", "卡尔瓦多斯 30 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#dfb46d",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-between-the-sheets",
            englishName: "Between the Sheets",
            chineseName: "床笫之间",
            ingredients: ["白朗姆 30 ml", "干邑 30 ml", "三秒酒 30 ml", "柠檬汁 20 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#e6cf9c",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-cardinale",
            englishName: "Cardinale",
            chineseName: "红衣主教",
            ingredients: ["金酒 40 ml", "干味美思 20 ml", "金巴利 10 ml"],
            tags: ["IBA 精选", "搅拌"],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入冰镇鸡尾酒杯；以柠檬皮装饰。",
            note: nil,
            accentHex: "#ca654e",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-champagne-cocktail",
            englishName: "Champagne Cocktail",
            chineseName: "香槟鸡尾酒",
            ingredients: ["香槟 90 ml", "干邑 10 ml", "安格仕苦精 2 dash", "方糖 1 块", "Grand Marnier 少量可选"],
            tags: ["IBA 精选", "直接调和"],
            glass: "香槟杯",
            method: "杯中放方糖并滴上苦精，加入干邑与可选的 Grand Marnier，缓缓倒入冰镇香槟；以橙皮和酒渍樱桃装饰。",
            note: nil,
            accentHex: "#e9d49a",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-hanky-panky",
            englishName: "Hanky Panky",
            chineseName: "汉基潘基",
            ingredients: ["金酒 45 ml", "甜味美思 45 ml", "费奈特 7.5 ml"],
            tags: ["IBA 精选", "搅拌"],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入冰镇鸡尾酒杯；以橙皮装饰。",
            note: nil,
            accentHex: "#a6573e",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-jungle-bird",
            englishName: "Jungle Bird",
            chineseName: "丛林鸟",
            ingredients: ["黑朗姆 45 ml", "金巴利 22.5 ml", "菠萝汁 45 ml", "青柠汁 15 ml", "德梅拉拉糖浆 15 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "岩石杯",
            method: "加冰摇匀，过滤入盛冰的岩石杯；以菠萝角装饰。",
            note: nil,
            accentHex: "#bf6841",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-kir",
            englishName: "Kir",
            chineseName: "基尔",
            ingredients: ["黑醋栗利口酒 10 ml", "干白葡萄酒 90 ml"],
            tags: ["IBA 精选", "直接调和"],
            glass: "葡萄酒杯",
            method: "先倒入黑醋栗利口酒，再缓缓加入干白葡萄酒。",
            note: nil,
            accentHex: "#a94a66",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-lemon-drop-martini",
            englishName: "Lemon Drop Martini",
            chineseName: "柠檬滴马天尼",
            ingredients: ["伏特加 30 ml", "三秒酒 20 ml", "柠檬汁 15 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#e6d381",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-martinez",
            englishName: "Martinez",
            chineseName: "马丁内斯",
            ingredients: ["金酒 45 ml", "甜味美思 45 ml", "马拉斯奇诺 1 吧勺", "橙味苦精 2 dash"],
            tags: ["IBA 精选", "搅拌"],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入冰镇鸡尾酒杯；以柠檬皮装饰。",
            note: nil,
            accentHex: "#aa593e",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-monkey-gland",
            englishName: "Monkey Gland",
            chineseName: "猴腺",
            ingredients: ["金酒 45 ml", "橙汁 45 ml", "苦艾酒 1 汤匙", "石榴糖浆 1 汤匙"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#d3995b",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-naked-and-famous",
            englishName: "Naked and Famous",
            chineseName: "赤裸与名声",
            ingredients: ["梅斯卡尔 22.5 ml", "黄查特酒 22.5 ml", "阿佩罗 22.5 ml", "青柠汁 22.5 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#de9b61",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-old-cuban",
            englishName: "Old Cuban",
            chineseName: "老古巴",
            ingredients: ["薄荷 6 到 8 片", "陈年朗姆 45 ml", "青柠汁 22.5 ml", "糖浆 30 ml", "安格仕苦精 2 dash", "香槟或普罗塞克 60 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "薄荷、朗姆、青柠汁、糖浆与苦精加冰摇匀，过滤入冰镇杯，最后加入起泡酒；以薄荷枝装饰。",
            note: nil,
            accentHex: "#b89c5a",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-paradise",
            englishName: "Paradise",
            chineseName: "天堂",
            ingredients: ["金酒 30 ml", "杏子白兰地 20 ml", "橙汁 15 ml"],
            tags: ["IBA 精选", "摇和"],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入冰镇鸡尾酒杯。",
            note: nil,
            accentHex: "#e7a569",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-stinger",
            englishName: "Stinger",
            chineseName: "毒刺",
            ingredients: ["干邑 50 ml", "白薄荷利口酒 20 ml"],
            tags: ["IBA 精选", "搅拌"],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入冰镇鸡尾酒杯；可用薄荷叶装饰。",
            note: nil,
            accentHex: "#d4c6ab",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "iba-vieux-carre",
            englishName: "Vieux Carré",
            chineseName: "老广场",
            ingredients: ["黑麦威士忌 30 ml", "干邑 30 ml", "甜味美思 30 ml", "廊酒 1 吧勺", "佩乔氏苦精 2 dash"],
            tags: ["IBA 精选", "搅拌"],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入冰镇鸡尾酒杯；以橙皮和酒渍樱桃装饰。",
            note: nil,
            accentHex: "#b87345",
            isUserCreated: false
        )
    ]
}
