import Foundation

enum WorldCocktailData {
    static let recipes: [CocktailRecipe] = [
        CocktailRecipe(
            id: "world-001-long-island-iced-tea",
            englishName: "Long Island Iced Tea",
            chineseName: "长岛冰茶",
            ingredients: [
                "伏特加 15 ml",
                "金酒 15 ml",
                "白朗姆 15 ml",
                "龙舌兰 15 ml",
                "橙味利口酒 15 ml",
                "柠檬汁 25 ml",
                "糖浆 20 ml",
                "可乐补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "伏特加",
                "朗姆",
                "龙舌兰",
                "酸爽",
                "长饮",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-002-margarita",
            englishName: "Margarita",
            chineseName: "玛格丽特",
            ingredients: [
                "龙舌兰 50 ml",
                "橙味利口酒 20 ml",
                "青柠汁 15 ml",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，盐边杯。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-003-tommys-margarita",
            englishName: "Tommy’s Margarita",
            chineseName: "汤米玛格丽特",
            ingredients: [
                "龙舌兰 60 ml",
                "青柠汁 30 ml",
                "龙舌兰糖浆 30 ml",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-004-mojito",
            englishName: "Mojito",
            chineseName: "莫吉托",
            ingredients: [
                "白朗姆 45 ml",
                "青柠汁 20 ml",
                "糖浆 15 ml",
                "薄荷 6 到 8 片",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "杯中轻压薄荷后加冰直调。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-005-daiquiri",
            englishName: "Daiquiri",
            chineseName: "代基里",
            ingredients: [
                "白朗姆 60 ml",
                "青柠汁 20 ml",
                "糖浆 15 ml",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入杯。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-006-cuba-libre",
            englishName: "Cuba Libre",
            chineseName: "自由古巴",
            ingredients: [
                "白朗姆 50 ml",
                "青柠汁 10 ml",
                "可乐补满",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-007-pina-colada",
            englishName: "Piña Colada",
            chineseName: "椰林飘香",
            ingredients: [
                "白朗姆 50 ml",
                "椰浆 30 ml",
                "菠萝汁 50 ml",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "奶油",
            ],
            glass: "岩石杯或高球杯",
            method: "与冰块一起搅打后倒入杯中。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-008-mai-tai",
            englishName: "Mai Tai",
            chineseName: "迈泰",
            ingredients: [
                "朗姆 60 ml",
                "橙味利口酒 15 ml",
                "杏仁糖浆 15 ml",
                "青柠汁 30 ml",
                "糖浆 7.5 ml",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-009-zombie",
            englishName: "Zombie",
            chineseName: "僵尸",
            ingredients: [
                "白朗姆 30 ml",
                "深色朗姆 30 ml",
                "过量朗姆 15 ml",
                "青柠汁 20 ml",
                "葡萄柚汁 30 ml",
                "肉桂糖浆 15 ml",
                "石榴糖浆 5 ml",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-010-hurricane",
            englishName: "Hurricane",
            chineseName: "飓风",
            ingredients: [
                "朗姆 60 ml",
                "百香果糖浆 30 ml",
                "柠檬汁 30 ml",
                "橙汁 30 ml",
                "石榴糖浆 10 ml",
            ],
            tags: [
                "世界经典",
                "朗姆",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#D18B48",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-011-gin-and-tonic",
            englishName: "Gin and Tonic",
            chineseName: "金汤力",
            ingredients: [
                "金酒 45 ml",
                "汤力水 120 到 150 ml",
                "柠檬片或青柠片",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-012-dry-martini",
            englishName: "Dry Martini",
            chineseName: "干马天尼",
            ingredients: [
                "金酒 60 ml",
                "干味美思 10 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "利口酒",
            ],
            glass: "马天尼杯",
            method: "加冰搅拌，过滤入冰镇杯，以橄榄或柠檬皮装饰。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-013-vodka-martini",
            englishName: "Vodka Martini",
            chineseName: "伏特加马天尼",
            ingredients: [
                "伏特加 60 ml",
                "干味美思 10 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "利口酒",
            ],
            glass: "马天尼杯",
            method: "加冰搅拌或摇匀，过滤入冰镇杯。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-014-vesper",
            englishName: "Vesper",
            chineseName: "维斯帕",
            ingredients: [
                "金酒 45 ml",
                "伏特加 15 ml",
                "Lillet Blanc 7.5 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "伏特加",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀或搅拌，过滤入冰镇杯。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-015-negroni",
            englishName: "Negroni",
            chineseName: "尼格罗尼",
            ingredients: [
                "金酒 30 ml",
                "金巴利 30 ml",
                "甜味美思 30 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰搅拌。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-016-tom-collins",
            englishName: "Tom Collins",
            chineseName: "汤姆柯林斯",
            ingredients: [
                "金酒 45 ml",
                "柠檬汁 30 ml",
                "糖浆 15 ml",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "长饮",
            ],
            glass: "高球杯",
            method: "高球杯加冰直调。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-017-john-collins",
            englishName: "John Collins",
            chineseName: "约翰柯林斯",
            ingredients: [
                "金酒 45 ml",
                "柠檬汁 30 ml",
                "糖浆 15 ml",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "长饮",
            ],
            glass: "高球杯",
            method: "高球杯加冰直调。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-018-gin-fizz",
            englishName: "Gin Fizz",
            chineseName: "金菲士",
            ingredients: [
                "金酒 45 ml",
                "柠檬汁 30 ml",
                "糖浆 10 ml",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "前三项加冰摇匀，倒入杯中后加苏打水。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-019-ramos-gin-fizz",
            englishName: "Ramos Gin Fizz",
            chineseName: "拉莫斯金菲士",
            ingredients: [
                "金酒 45 ml",
                "柠檬汁 15 ml",
                "青柠汁 15 ml",
                "糖浆 30 ml",
                "奶油 60 ml",
                "蛋白 1 个",
                "橙花水少量",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "奶油",
                "酸爽",
                "长饮",
            ],
            glass: "鸡尾酒杯",
            method: "充分摇匀后加苏打水。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-020-bees-knees",
            englishName: "Bee’s Knees",
            chineseName: "蜂之膝",
            ingredients: [
                "金酒 52.5 ml",
                "柠檬汁 22.5 ml",
                "蜂蜜糖浆 22.5 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-021-aviation",
            englishName: "Aviation",
            chineseName: "航空",
            ingredients: [
                "金酒 45 ml",
                "黑樱桃利口酒 15 ml",
                "紫罗兰利口酒 5 ml",
                "柠檬汁 15 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-022-clover-club",
            englishName: "Clover Club",
            chineseName: "三叶草俱乐部",
            ingredients: [
                "金酒 45 ml",
                "柠檬汁 15 ml",
                "覆盆子糖浆 15 ml",
                "蛋白 1 个",
            ],
            tags: [
                "世界经典",
                "金酒",
                "奶油",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "先干摇，再加冰摇匀。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-023-south-side",
            englishName: "South Side",
            chineseName: "南边",
            ingredients: [
                "金酒 60 ml",
                "柠檬汁 30 ml",
                "糖浆 15 ml",
                "薄荷叶",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，过滤入杯。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-024-bramble",
            englishName: "Bramble",
            chineseName: "荆棘",
            ingredients: [
                "金酒 50 ml",
                "柠檬汁 25 ml",
                "糖浆 12.5 ml",
                "黑莓利口酒 15 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "碎冰杯中制作，黑莓利口酒最后淋入。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-025-white-lady",
            englishName: "White Lady",
            chineseName: "白色佳人",
            ingredients: [
                "金酒 40 ml",
                "橙味利口酒 30 ml",
                "柠檬汁 20 ml",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-026-moscow-mule",
            englishName: "Moscow Mule",
            chineseName: "莫斯科骡子",
            ingredients: [
                "伏特加 45 ml",
                "青柠汁 10 ml",
                "姜汁啤酒 120 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "酸爽",
                "长饮",
            ],
            glass: "高球杯",
            method: "铜杯或高球杯加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-027-cosmopolitan",
            englishName: "Cosmopolitan",
            chineseName: "大都会",
            ingredients: [
                "伏特加 40 ml",
                "橙味利口酒 15 ml",
                "青柠汁 15 ml",
                "蔓越莓汁 30 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-028-espresso-martini",
            englishName: "Espresso Martini",
            chineseName: "浓缩咖啡马天尼",
            ingredients: [
                "伏特加 50 ml",
                "咖啡利口酒 30 ml",
                "糖浆 10 ml",
                "浓缩咖啡 30 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "咖啡",
                "利口酒",
            ],
            glass: "马天尼杯",
            method: "加冰摇匀，过滤入马天尼杯。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-029-black-russian",
            englishName: "Black Russian",
            chineseName: "黑俄罗斯",
            ingredients: [
                "伏特加 50 ml",
                "咖啡利口酒 20 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "咖啡",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "杯中加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-030-white-russian",
            englishName: "White Russian",
            chineseName: "白俄罗斯",
            ingredients: [
                "伏特加 50 ml",
                "咖啡利口酒 20 ml",
                "奶油 30 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "咖啡",
                "奶油",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "杯中加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-031-bloody-mary",
            englishName: "Bloody Mary",
            chineseName: "血腥玛丽",
            ingredients: [
                "伏特加 45 ml",
                "番茄汁 90 ml",
                "柠檬汁 15 ml",
                "伍斯特酱",
                "辣椒酱",
                "盐",
                "胡椒",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "酸爽",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-032-screwdriver",
            englishName: "Screwdriver",
            chineseName: "螺丝刀",
            ingredients: [
                "伏特加 45 ml",
                "橙汁 120 到 150 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-033-sea-breeze",
            englishName: "Sea Breeze",
            chineseName: "海风",
            ingredients: [
                "伏特加 40 ml",
                "蔓越莓汁 120 ml",
                "西柚汁 30 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "酸爽",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-034-sex-on-the-beach",
            englishName: "Sex on the Beach",
            chineseName: "性感沙滩",
            ingredients: [
                "伏特加 40 ml",
                "桃味利口酒 20 ml",
                "橙汁 40 ml",
                "蔓越莓汁 40 ml",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-035-blue-lagoon",
            englishName: "Blue Lagoon",
            chineseName: "蓝色泻湖",
            ingredients: [
                "伏特加 40 ml",
                "蓝橙酒 20 ml",
                "柠檬汽水补满",
            ],
            tags: [
                "世界经典",
                "伏特加",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#7FA6BD",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-036-old-fashioned",
            englishName: "Old Fashioned",
            chineseName: "古典鸡尾酒",
            ingredients: [
                "波本或黑麦威士忌 45 ml",
                "方糖 1 块",
                "苦精 2 到 3 滴",
                "水少量",
            ],
            tags: [
                "世界经典",
                "威士忌",
            ],
            glass: "岩石杯或高球杯",
            method: "杯中搅拌。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-037-whiskey-sour",
            englishName: "Whiskey Sour",
            chineseName: "威士忌酸",
            ingredients: [
                "威士忌 45 ml",
                "柠檬汁 25 ml",
                "糖浆 20 ml",
                "蛋白可选",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "奶油",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-038-manhattan",
            englishName: "Manhattan",
            chineseName: "曼哈顿",
            ingredients: [
                "黑麦或波本 50 ml",
                "甜味美思 20 ml",
                "苦精 1 到 2 滴",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰搅拌，过滤入杯。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-039-rob-roy",
            englishName: "Rob Roy",
            chineseName: "罗伯罗伊",
            ingredients: [
                "苏格兰威士忌 50 ml",
                "甜味美思 20 ml",
                "苦精 1 到 2 滴",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰搅拌。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-040-mint-julep",
            englishName: "Mint Julep",
            chineseName: "薄荷朱利普",
            ingredients: [
                "波本 60 ml",
                "糖浆 10 ml",
                "薄荷叶",
                "碎冰",
            ],
            tags: [
                "世界经典",
                "威士忌",
            ],
            glass: "岩石杯或高球杯",
            method: "杯中轻压薄荷后加入碎冰和波本搅拌。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-041-boulevardier",
            englishName: "Boulevardier",
            chineseName: "林荫大道",
            ingredients: [
                "波本 45 ml",
                "金巴利 30 ml",
                "甜味美思 30 ml",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰搅拌。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-042-penicillin",
            englishName: "Penicillin",
            chineseName: "盘尼西林",
            ingredients: [
                "苏格兰威士忌 60 ml",
                "柠檬汁 22.5 ml",
                "蜂蜜姜糖浆 22.5 ml",
                "泥煤威士忌少量漂浮",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "摇匀后漂浮泥煤威士忌。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-043-new-york-sour",
            englishName: "New York Sour",
            chineseName: "纽约酸",
            ingredients: [
                "威士忌 60 ml",
                "柠檬汁 25 ml",
                "糖浆 20 ml",
                "红酒 15 ml 漂浮",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "前三项摇匀后加入红酒。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-044-rusty-nail",
            englishName: "Rusty Nail",
            chineseName: "生锈钉",
            ingredients: [
                "苏格兰威士忌 45 ml",
                "杜林标 25 ml",
            ],
            tags: [
                "世界经典",
                "威士忌",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-045-sazerac",
            englishName: "Sazerac",
            chineseName: "萨泽拉克",
            ingredients: [
                "黑麦威士忌 50 ml",
                "方糖 1 块",
                "Peychaud’s 苦精",
                "苦艾酒洗杯",
            ],
            tags: [
                "世界经典",
                "威士忌",
            ],
            glass: "鸡尾酒杯",
            method: "搅拌后倒入洗杯。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-046-irish-coffee",
            englishName: "Irish Coffee",
            chineseName: "爱尔兰咖啡",
            ingredients: [
                "爱尔兰威士忌 40 ml",
                "热咖啡 90 ml",
                "糖 10 ml",
                "奶油漂浮",
            ],
            tags: [
                "世界经典",
                "威士忌",
                "咖啡",
                "奶油",
            ],
            glass: "热饮杯",
            method: "热饮制作。",
            note: nil,
            accentHex: "#9A5C3E",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-047-paloma",
            englishName: "Paloma",
            chineseName: "帕洛玛",
            ingredients: [
                "龙舌兰 50 ml",
                "青柠汁 10 ml",
                "西柚汽水补满",
                "盐边可选",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-048-tequila-sunrise",
            englishName: "Tequila Sunrise",
            chineseName: "龙舌兰日出",
            ingredients: [
                "龙舌兰 45 ml",
                "橙汁 90 ml",
                "石榴糖浆 15 ml",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调，石榴糖浆最后慢慢倒入。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-049-el-diablo",
            englishName: "El Diablo",
            chineseName: "魔鬼",
            ingredients: [
                "龙舌兰 45 ml",
                "黑醋栗利口酒 15 ml",
                "青柠汁 15 ml",
                "姜汁啤酒补满",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
                "酸爽",
                "长饮",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-050-batanga",
            englishName: "Batanga",
            chineseName: "巴坦加",
            ingredients: [
                "龙舌兰 50 ml",
                "青柠汁 10 ml",
                "可乐补满",
                "盐边可选",
            ],
            tags: [
                "世界经典",
                "龙舌兰",
                "酸爽",
                "长饮",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#D0A052",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-051-americano",
            englishName: "Americano",
            chineseName: "美式",
            ingredients: [
                "金巴利 30 ml",
                "甜味美思 30 ml",
                "苏打水补满",
            ],
            tags: [
                "世界经典",
                "长饮",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#31535A",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-052-aperol-spritz",
            englishName: "Aperol Spritz",
            chineseName: "阿佩罗司普瑞兹",
            ingredients: [
                "阿佩罗 60 ml",
                "普罗塞克 90 ml",
                "苏打水 30 ml",
            ],
            tags: [
                "世界经典",
                "长饮",
                "起泡",
                "利口酒",
            ],
            glass: "岩石杯或高球杯",
            method: "加冰直调。",
            note: nil,
            accentHex: "#C9A65B",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-053-bellini",
            englishName: "Bellini",
            chineseName: "贝利尼",
            ingredients: [
                "桃泥 50 ml",
                "普罗塞克 100 ml",
            ],
            tags: [
                "世界经典",
                "长饮",
                "起泡",
            ],
            glass: "鸡尾酒杯",
            method: "轻轻搅匀。",
            note: nil,
            accentHex: "#C9A65B",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-054-mimosa",
            englishName: "Mimosa",
            chineseName: "含羞草",
            ingredients: [
                "香槟或起泡酒 75 ml",
                "橙汁 75 ml",
            ],
            tags: [
                "世界经典",
                "长饮",
                "起泡",
            ],
            glass: "鸡尾酒杯",
            method: "轻轻搅匀。",
            note: nil,
            accentHex: "#C9A65B",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-055-french-75",
            englishName: "French 75",
            chineseName: "法式 75",
            ingredients: [
                "金酒 30 ml",
                "柠檬汁 15 ml",
                "糖浆 15 ml",
                "香槟补满",
            ],
            tags: [
                "世界经典",
                "金酒",
                "酸爽",
                "长饮",
                "起泡",
            ],
            glass: "鸡尾酒杯",
            method: "前三项摇匀后加香槟。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-056-sidecar",
            englishName: "Sidecar",
            chineseName: "边车",
            ingredients: [
                "干邑 50 ml",
                "橙味利口酒 20 ml",
                "柠檬汁 20 ml",
            ],
            tags: [
                "世界经典",
                "白兰地",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀，糖边杯可选。",
            note: nil,
            accentHex: "#B76E54",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-057-brandy-alexander",
            englishName: "Brandy Alexander",
            chineseName: "白兰地亚历山大",
            ingredients: [
                "白兰地 30 ml",
                "可可利口酒 30 ml",
                "奶油 30 ml",
            ],
            tags: [
                "世界经典",
                "白兰地",
                "奶油",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#B76E54",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-058-pisco-sour",
            englishName: "Pisco Sour",
            chineseName: "皮斯科酸",
            ingredients: [
                "皮斯科 60 ml",
                "青柠汁 30 ml",
                "糖浆 20 ml",
                "蛋白 1 个",
                "苦精少量",
            ],
            tags: [
                "世界经典",
                "白兰地",
                "奶油",
                "酸爽",
            ],
            glass: "鸡尾酒杯",
            method: "先干摇，再加冰摇。",
            note: nil,
            accentHex: "#B76E54",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-059-caipirinha",
            englishName: "Caipirinha",
            chineseName: "卡皮莉亚",
            ingredients: [
                "卡莎萨 60 ml",
                "青柠 1 个切块",
                "白糖 3 到 4 茶匙",
            ],
            tags: [
                "世界经典",
                "酸爽",
            ],
            glass: "岩石杯或高球杯",
            method: "压碎后加碎冰搅拌。",
            note: nil,
            accentHex: "#31535A",
            isUserCreated: false
        ),
        CocktailRecipe(
            id: "world-060-singapore-sling",
            englishName: "Singapore Sling",
            chineseName: "新加坡司令",
            ingredients: [
                "金酒 30 ml",
                "樱桃白兰地 15 ml",
                "橙味利口酒 7.5 ml",
                "DOM 7.5 ml",
                "菠萝汁 120 ml",
                "青柠汁 15 ml",
                "石榴糖浆 10 ml",
                "苦精 1 滴",
            ],
            tags: [
                "世界经典",
                "金酒",
                "白兰地",
                "酸爽",
                "利口酒",
            ],
            glass: "鸡尾酒杯",
            method: "加冰摇匀。",
            note: nil,
            accentHex: "#79A883",
            isUserCreated: false
        )
    ]
}
