// Generated by npm run build:weapp; edit the shared BarWeb source instead.
const globalThis = {};
let BarCore, BarTasteData, BarTaste, BarI18n, BarArt;
const hasOwn = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
/* Pure data and matching rules, shared by the browser and both Apple apps. */
(() => {
  const categories = {
    spirit: "酒类",
    juice: "果汁",
    syrup: "糖浆与糖",
    mixer: "饮料与乳品",
    other: "水果与其他",
  };
  const aliases = {
    深色朗姆: "黑朗姆",
    苏格兰威士忌: "苏格兰",
    黑麦威士忌: "黑麦",
    普罗塞克: "普洛赛克",
    葡萄柚汁: "西柚汁",
    薄荷叶: "薄荷",
    冷浓缩咖啡: "浓缩咖啡",
    热咖啡: "咖啡",
    普通糖浆: "糖浆",
    白糖: "糖",
    盐边杯: "盐",
    盐边: "盐",
  };
  const parents = {
    白朗姆: "朗姆",
    黑朗姆: "朗姆",
    椰子朗姆: "朗姆",
    过量朗姆: "朗姆",
    波本: "威士忌",
    黑麦: "威士忌",
    苏格兰: "威士忌",
    爱尔兰威士忌: "威士忌",
    泥煤威士忌: "威士忌",
    干邑: "白兰地",
    干味美思: "味美思",
    甜味美思: "味美思",
    香槟: "起泡酒",
    普洛赛克: "起泡酒",
    君度: "橙味利口酒",
    三秒酒: "橙味利口酒",
    浓缩咖啡: "咖啡",
  };
  const clean = (text) => text.trim().replace(/\s+/g, " ");
  const canonical = (name) => {
    const normalized = globalThis.BarI18n?.canonicalIngredient(clean(name)) || clean(name);
    return hasOwn(aliases, normalized) ? aliases[normalized] : normalized;
  };
  function category(name) {
    if (name === "啤酒") return "spirit";
    if (/糖浆|糖$/.test(name)) return "syrup";
    if (/汁$/.test(name)) return "juice";
    if (
      /汽水|啤酒|汤力|苏打|雪碧|可乐|红茶|能量饮料|奶|咖啡|椰浆/.test(name) &&
      !/利口酒|百利/.test(name)
    )
      return "mixer";
    if (
      /酒|伏特加|威士忌|白兰地|朗姆|金巴利|阿佩罗|普洛赛克|香槟|干邑|波本|黑麦|苏格兰|君度|三秒|味美思|百利甜|Amaro|Lillet|杜林标|DOM|皮斯科|卡莎萨|龙舌兰|柑曼怡|马拉斯奇诺/.test(
        name,
      )
    )
      return "spirit";
    return "other";
  }
  function ingredient(raw) {
    // Preserve the exact original amount, alternatives, and optional markers.
    const substitution = raw.startsWith("没有");
    const text = raw.replace(/^没有龙舌兰糖浆可用/, "");
    const marker = text.search(/\d|补满|少量|可选|漂浮|洗杯|to top up|a little|optional|float|glass rinse/i);
    let names = (marker < 0 ? text : text.slice(0, marker)).trim();
    names = names.replace("波本或黑麦威士忌", "波本或黑麦");
    const types = names.split(/或|\s+or\s+/i).map(canonical);
    return {
      raw,
      types,
      amount: marker < 0 ? "按配方" : text.slice(marker).trim(),
      optional: /可选|\boptional\b/i.test(raw) || substitution,
      substitution,
      category: category(types[0]),
    };
  }
  function satisfies(owned, required) {
    for (let current = canonical(owned); current; current = hasOwn(parents, current) ? parents[current] : null)
      if (current === canonical(required)) return true;
    return false;
  }
  function match(recipe, inventory, selected = Object.keys(categories)) {
    const checked = new Set(selected);
    const missing = new Map();
    const unchecked = [];
    for (const part of recipe.parts || recipe.ingredients.map(ingredient)) {
      if (part.optional) continue;
      if (!checked.has(part.category)) {
        unchecked.push(part);
        continue;
      }
      if (
        !inventory.some((item) =>
          part.types.some((type) => satisfies(item.type, type)),
        )
      )
        missing.set([...part.types].sort().join("|"), part);
    }
    return {
      missing: [...missing.values()],
      unchecked,
      count: missing.size,
      checked: checked.size > 0,
    };
  }
  function migrate(names, catalog) {
    return [...new Set(names)]
      .filter((n) => typeof n === "string" && n.trim())
      .map((name, index) => {
        const type = canonical(name);
        return {
          id: `legacy-${index}`,
          name,
          type: catalog.some((t) => t.name === type) ? type : "",
          color: "#79a883",
          shape: "bottle",
          drawing: [],
          legacy: true,
        };
      });
  }
  const glassNames = {
    coupe: "碟形杯",
    martini: "马天尼杯",
    highball: "高球杯",
    rocks: "古典杯",
    wine: "葡萄酒杯",
    hurricane: "飓风杯",
    mug: "热饮杯",
    shot: "烈酒杯",
    margarita: "玛格丽特杯",
    bowl: "分享碗",
  };
  const bottleShapes = { bottle: '经典长瓶', round: '圆肚酒瓶', whiskey: '方肩威士忌瓶', gin: '平肩金酒瓶', vodka: '圆肩伏特加瓶', tequila: '矮身龙舌兰瓶', rum: '修长朗姆瓶', carton: '果汁纸盒', jar: '糖浆罐' };
  const validColor = value => /^#[0-9a-f]{6}$/i.test(value);
  function validVisual(v) {
    return v && typeof v === 'object' && !Array.isArray(v) &&
      (v.layers === undefined || (Array.isArray(v.layers) && v.layers.length === 2 && v.layers.every(validColor))) &&
      (v.garnish === undefined || ['none','orange','lime','lemon','mint','olive','coffee'].includes(v.garnish)) &&
      ['ice','foam'].every(k => v[k] === undefined || typeof v[k] === 'boolean');
  }
  function drinkAppearance(recipe = {}, selected = {}) {
    const defaultGlass = /飓风/.test(recipe.glass) ? 'hurricane' : /热饮/.test(recipe.glass) ? 'mug'
      : /烈酒/.test(recipe.glass) ? 'shot' : /玛格丽特/.test(recipe.glass) ? 'margarita'
      : /碗/.test(recipe.glass) ? 'bowl' : /高球|铜|柯林/.test(recipe.glass) ? "highball"
      : /岩石|古典/.test(recipe.glass) ? "rocks"
      : /马天尼|鸡尾酒/.test(recipe.glass) ? "martini"
      : /葡萄酒/.test(recipe.glass) ? "wine" : "coupe";
    return {
      ...(recipe.appearance ? { visual: { ...recipe.appearance } } : {}),
      ...(selected.visual ? { visual: { ...selected.visual } } : {}),
      glass: hasOwn(glassNames, selected.glass) ? selected.glass : defaultGlass,
      color: /^#[0-9a-f]{6}$/i.test(selected.color) ? selected.color
        : validColor(recipe.appearance?.color) ? recipe.appearance.color
        : /^#[0-9a-f]{6}$/i.test(recipe.accentHex) ? recipe.accentHex : "#da9561",
    };
  }
  function journalMonth(month, logs = []) {
    const [year, number] = month.split("-").map(Number);
    // UTC is used only for calendar arithmetic; diary dates remain local date strings.
    const first = new Date(0);
    first.setUTCFullYear(year, number - 1, 1);
    const offset = (first.getUTCDay() + 6) % 7;
    const last = new Date(first);
    last.setUTCMonth(number, 0);
    const days = Array.from({ length: last.getUTCDate() }, (_, index) => {
      const date = `${month}-${String(index + 1).padStart(2, "0")}`;
      return { date, day: index + 1, entries: [] };
    });
    for (const log of logs) {
      const day = days[Number(log.date.slice(8)) - 1];
      if (day?.date === log.date) day.entries.push(log);
    }
    const cells = Array(Math.ceil((offset + days.length) / 7) * 7).fill(null);
    days.forEach((day, index) => { cells[offset + index] = day; });
    const shift = (delta) => {
      const date = new Date(first);
      date.setUTCMonth(date.getUTCMonth() + delta);
      const y = date.getUTCFullYear();
      return y < 1 || y > 9999 ? null : `${String(y).padStart(4, "0")}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`;
    };
    return { year, number, cells, previous: shift(-1), next: shift(1),
      count: days.reduce((sum, day) => sum + day.entries.length, 0) };
  }
  const blankState = () => ({
    version: 1,
    inventory: [],
    favorites: [],
    customRecipes: [],
    logs: [],
    taste: { onboarding: null, ratings: [] },
    theme: "bar",
    locale: "zh-CN",
    migrated: false,
    guideVersion: 0,
  });
  function validateState(value) {
    if (
      !value ||
      value.version !== 1 ||
      !["inventory", "favorites", "customRecipes", "logs"].every((k) =>
        Array.isArray(value[k]),
      )
    )
      throw new Error("这不是有效的吧台备份文件。");
    if (
      value.inventory.length > 1000 ||
      value.customRecipes.length > 1000 ||
      value.logs.length > 10000
    )
      throw new Error("备份内容过大。");
    const isText = (x) => typeof x === "string" && x.length <= 5000;
    if (['nativeImportedRecipeIDs', 'nativeMigrationSources'].some(key => value[key] !== undefined &&
      (!Array.isArray(value[key]) || value[key].length > 10000 || !value[key].every(isText))))
      throw new Error("迁移记录格式不正确。");
    if (
      !value.inventory.every(
        (i) =>
          i &&
          isText(i.id) &&
          isText(i.name) &&
          isText(i.type) &&
          /^#[0-9a-f]{6}$/i.test(i.color) &&
          hasOwn(bottleShapes, i.shape) &&
          Array.isArray(i.drawing) &&
          i.drawing.length <= 200 &&
          i.drawing.every(
            (s) =>
              Array.isArray(s) &&
              s.length <= 2000 &&
              s.every(
                (p) =>
                  Array.isArray(p) &&
                  p.length === 2 &&
                  p.every((v) => Number.isFinite(v) && v >= 0 && v <= 200),
              ),
          ),
      )
    )
      throw new Error("库存数据格式不正确。");
    if (
      !value.favorites.every(isText) ||
      !value.customRecipes.every(
        (r) =>
          r &&
          isText(r.id) &&
          /^user-[a-zA-Z0-9-]+$/.test(r.id) &&
          isText(r.chineseName) &&
          isText(r.englishName) &&
          isText(r.method) &&
          isText(r.glass) &&
          (r.photo === undefined || (typeof r.photo === 'string' && r.photo.length <= 180000 && /^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(r.photo))) &&
          (r.appearance === undefined || (validVisual(r.appearance) && validColor(r.appearance.color))) &&
          Array.isArray(r.ingredients) &&
          r.ingredients.length > 0 &&
          r.ingredients.length <= 100 &&
          r.ingredients.every(isText) &&
          Array.isArray(r.tags) &&
          r.tags.every(isText),
      )
    )
      throw new Error("配方数据格式不正确。");
    if (
      !value.logs.every(
        (l) =>
          l &&
          isText(l.id) &&
          /^\d{4}-\d{2}-\d{2}$/.test(l.date) &&
          isText(l.name) &&
          isText(l.note) &&
          (l.recipeID === undefined || isText(l.recipeID)) &&
          (l.visual === undefined || validVisual(l.visual)) &&
          (l.photos === undefined || (Array.isArray(l.photos) && l.photos.length <= (l.legacyPhotos === true ? 256 : 3) && l.photos.every(p => typeof p === 'string' && p.length <= 180000 && /^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(p)))) &&
          ((l.glass === undefined && l.color === undefined) ||
            (hasOwn(glassNames, l.glass) && /^#[0-9a-f]{6}$/i.test(l.color))),
      )
    )
      throw new Error("日记数据格式不正确。");
    if (
      new Set(value.inventory.map((i) => i.id)).size !==
        value.inventory.length ||
      new Set(value.customRecipes.map((r) => r.id)).size !==
        value.customRecipes.length
    )
      throw new Error("备份包含重复编号。");
    return {
      ...blankState(),
      ...value,
      taste: value.taste === undefined ? { onboarding: null, ratings: [] } : BarTaste.validate(value.taste),
      customRecipes: value.customRecipes.map(r => ({
        id: r.id, chineseName: r.chineseName, englishName: r.englishName,
        ingredients: r.ingredients, tags: r.tags, glass: r.glass,
        method: r.method, note: typeof r.note === 'string' ? r.note : null,
        accentHex: /^#[0-9a-f]{6}$/i.test(r.accentHex) ? r.accentHex : '#b87b5d',
        ...(r.appearance ? { appearance: { color: r.appearance.color, layers: r.appearance.layers,
          garnish: r.appearance.garnish, ice: r.appearance.ice, foam: r.appearance.foam } } : {}),
        ...(r.photo ? { photo: r.photo } : {}),
        isUserCreated: true,
      })),
      theme: ["bar", "light", "dark"].includes(value.theme)
        ? value.theme
        : "bar",
      guideVersion: value.guideVersion === 1 ? 1 : 0,
      locale: value.locale === "en" ? "en" : "zh-CN",
    };
  }
  globalThis.BarCore = {
    categories,
    canonical,
    category,
    ingredient,
    satisfies,
    match,
    migrate,
    blankState,
    validateState,
    glassNames,
    bottleShapes,
    drinkAppearance,
    journalMonth,
  };
})();

BarCore = globalThis.BarCore;
/* Editorial starting estimates, not laboratory measurements or alcohol percentages.
   Order: sweet, sour, bitter, strength, fruity, herbal, smoky, body. */
(() => {
  const groups = [
    ["Amaro Nonino", [50,5,75,70,35,75,0,35]],
    ["绿查特酒", [65,5,45,90,15,100,0,30]],
    ["覆盆子利口酒", [85,25,5,30,100,5,0,35]],
    ["白可可利口酒", [90,0,15,35,0,10,0,65]],
    ["绿薄荷利口酒", [85,0,10,35,0,100,0,30]],
    ["罗勒", [0,5,10,0,0,100,0,0]],
    ["马拉斯奇诺", [80,10,15,55,70,20,0,30]],
    ["杏子白兰地", [70,5,5,65,85,5,0,35], "果味利口酒"],
    ["卡尔瓦多斯", [18,2,8,90,70,5,0,42], "白兰地"],
    ["Grand Marnier", [75,8,12,65,90,10,0,40], "果味利口酒"],
    ["费奈特", [20,0,95,80,5,95,0,35], "草本利口酒"],
    ["梅斯卡尔", [6,0,12,90,8,30,85,32], "龙舌兰"],
    ["黄查特酒", [70,3,35,80,10,100,0,35], "草本利口酒"],
    ["白薄荷利口酒", [85,0,8,40,0,100,0,30], "草本利口酒"],
    ["廊酒", [75,0,25,75,10,85,5,55], "草本利口酒"],
    ["金酒", [3,0,12,90,8,75,0,20], "金酒"],
    ["伏特加", [0,0,2,90,0,0,0,10], "伏特加"],
    ["威士忌|波本|黑麦|爱尔兰威士忌", [15,0,12,90,10,8,12,45], "威士忌"],
    ["苏格兰", [10,0,15,90,8,8,35,45], "威士忌"],
    ["泥煤威士忌", [6,0,20,90,5,8,95,45], "威士忌"],
    ["白朗姆|朗姆|卡莎萨", [12,0,3,90,12,8,0,30], "朗姆"],
    ["黑朗姆", [25,0,8,90,18,8,12,55], "朗姆"],
    ["陈年朗姆", [20,0,8,90,25,12,8,45], "朗姆"],
    ["过量朗姆", [12,0,5,100,12,8,5,40], "朗姆"],
    ["椰子朗姆", [65,0,0,50,65,0,0,50], "朗姆"],
    ["白兰地|干邑|皮斯科", [15,5,5,90,35,5,5,40], "白兰地"],
    ["龙舌兰", [8,0,10,90,8,35,5,30], "龙舌兰"],
    ["百利甜", [80,0,8,35,0,0,0,95], "奶油利口酒"],
    ["金巴利", [50,12,95,55,30,60,0,35], "开胃酒"],
    ["阿佩罗", [65,20,60,25,55,40,0,30], "开胃酒"],
    ["干味美思|Lillet Blanc", [18,18,35,35,25,70,0,25], "味美思"],
    ["甜味美思", [65,15,40,35,35,70,0,40], "味美思"],
    ["苦艾酒", [5,0,55,100,0,100,0,25], "草本利口酒"],
    ["杜林标|DOM", [75,0,25,75,10,85,5,55], "草本利口酒"],
    ["橙味利口酒|君度|三秒酒|蓝橙酒", [80,12,15,65,90,8,0,35], "果味利口酒"],
    ["黑醋栗利口酒|黑莓利口酒|黑樱桃利口酒|樱桃白兰地|桃味利口酒", [85,20,8,40,95,0,0,45], "果味利口酒"],
    ["紫罗兰利口酒", [80,0,5,40,20,70,0,35], "花香利口酒"],
    ["咖啡利口酒|可可利口酒", [80,0,55,40,0,0,0,65], "甜点利口酒"],
    ["红酒", [20,45,35,30,65,10,0,50], "葡萄酒"],
    ["干白葡萄酒", [10,55,10,30,45,8,0,18], "葡萄酒"],
    ["香槟|普洛赛克|起泡酒", [20,50,8,25,55,5,0,15], "起泡酒"],
    ["啤酒", [15,8,45,12,8,15,0,30], "啤酒"],
    ["柠檬汁|青柠汁|青柠", [5,100,5,0,75,0,0,10]],
    ["西柚汁", [35,65,45,0,95,0,0,15]],
    ["橙汁|菠萝汁|苹果汁", [65,40,3,0,100,0,0,25]],
    ["蔓越莓汁", [45,65,15,0,95,0,0,20]],
    ["番茄汁", [15,35,5,0,30,25,0,65]],
    ["桃泥", [75,25,0,0,100,0,0,65]],
    ["糖浆|糖|方糖|龙舌兰糖浆", [100,0,0,0,0,0,0,50]],
    ["德梅拉拉糖浆", [100,0,0,0,0,0,0,55]],
    ["石榴糖浆|覆盆子糖浆|百香果糖浆", [100,25,0,0,80,0,0,50]],
    ["蜂蜜糖浆|蜂蜜姜糖浆", [100,0,3,0,10,30,0,65]],
    ["杏仁糖浆", [100,0,5,0,5,10,0,75]],
    ["肉桂糖浆", [100,0,5,0,0,70,0,50]],
    ["汤力水", [50,10,60,0,10,15,0,5]],
    ["姜汁汽水|姜汁啤酒", [65,15,8,0,10,60,0,10]],
    ["可乐|冰红茶|能量饮料", [75,15,15,0,15,10,0,15]],
    ["雪碧|柠檬汽水|西柚汽水", [65,30,10,0,60,0,0,5]],
    ["水|苏打水|碎冰|盐", [0,0,0,0,0,0,0,0]],
    ["咖啡|浓缩咖啡", [0,15,90,0,0,10,8,45]],
    ["奶油|椰浆", [25,0,0,0,10,0,0,100]],
    ["牛奶|蛋白", [15,0,0,0,0,0,0,75]],
    ["薄荷", [0,0,8,0,0,100,0,0]],
    ["橙花水", [0,0,0,0,30,90,0,0]],
    ["苦精|Peychaud’s 苦精", [0,0,100,40,15,90,0,15]],
    ["安格仕苦精|橙味苦精|佩乔氏苦精", [0,0,100,40,15,90,0,15]],
    ["柠檬皮|柠檬片|青柠片", [0,60,15,0,90,15,0,0]],
    ["胡椒|辣椒酱|伍斯特酱", [5,15,15,0,0,65,0,20]],
  ];
  globalThis.BarTasteData = Object.fromEntries(groups.flatMap(([names, vector, base]) =>
    names.split("|").map(name => [name, { vector, base }])));
})();

BarTasteData = globalThis.BarTasteData;
/* Deterministic local taste estimates and preference learning. No network or AI. */
(() => {
  const dimensions = ["甜感", "酸感", "苦感", "酒感", "果香", "草本", "烟熏", "醇厚"];
  const weights = [1.2, 1.2, 1.2, 1.3, 1, 0.8, 0.8, 0.7];
  const neutral = [50, 50, 25, 45, 45, 25, 10, 40];
  const drinks = {
    lemonade: ["清新柠檬水", [45,80,10,30,70,15,5,20]],
    cola: ["可乐", [75,30,20,35,30,20,5,40]],
    coffee: ["黑咖啡", [15,30,75,50,15,30,15,65]],
    tropical: ["热带果汁", [70,45,10,30,90,10,5,50]],
  };
  const styles = {
    fresh: ["清爽", [40,65,20,30,65,40,5,20]],
    sweet: ["香甜", [80,30,10,35,55,20,5,55]],
    strong: ["浓烈", [30,25,40,80,25,35,25,60]],
    fruity: ["果香", [60,55,15,35,90,20,5,35]],
    dry: ["干爽", [15,35,35,55,30,50,10,25]],
    bitter: ["微苦", [30,30,75,45,30,55,15,40]],
  };
  const flavors = {
    coffee: ["咖啡", 2], lemon: ["柠檬", 1], orange: ["橙子", 4], berry: ["莓果", 4],
    mint: ["薄荷", 5], ginger: ["生姜", 5], coconut: ["椰子", 7], chocolate: ["巧克力", 7], smoky: ["烟熏", 6],
  };
  const palette = {
    lemon: ["柠檬", "#d6b958", [30,85,10,45,75,15,5,20]],
    orange: ["橙子", "#da945a", [65,50,15,45,85,15,5,30]],
    berry: ["莓果", "#b77189", [60,60,10,45,90,10,5,35]],
    mint: ["薄荷", "#78a891", [25,40,25,45,25,90,5,15]],
    ginger: ["生姜", "#bc975d", [30,30,25,45,25,75,10,30]],
    coffee: ["咖啡", "#956f59", [15,25,80,45,10,25,20,65]],
    coconut: ["椰子", "#b9ae90", [65,10,10,45,35,10,5,90]],
    chocolate: ["巧克力", "#916f78", [70,10,45,45,10,10,10,85]],
    smoky: ["烟熏", "#84969a", [20,15,45,45,10,35,90,55]],
  };
  const strengths = { light: ["轻柔", 25], balanced: ["适中", 45], bold: ["浓烈", 75] };
  const feedback = { sweet: ["太甜", 0, -25], sour: ["太酸", 1, -25], bitter: ["太苦", 2, -25], strong: ["太烈", 3, -25], weak: ["太淡", 3, 25] };
  const clamp = n => Math.max(0, Math.min(100, n));
  const vectorValid = v => Array.isArray(v) && v.length === 8 && v.every(n => Number.isFinite(n) && n >= 0 && n <= 100);
  const empty = () => ({ onboarding: null, ratings: [] });
  function validate(value) {
    const text = s => typeof s === "string" && s.length > 0 && s.length <= 200;
    const list = (items, choices) => Array.isArray(items) && items.length <= Object.keys(choices).length && new Set(items).size === items.length && items.every(k => hasOwn(choices, k));
    const o = value?.onboarding;
    const paletteMode = !!o && hasOwn(o, "palette");
    const validSeed = o === null || (o && (paletteMode
      ? list(o.palette, palette) && o.palette.length > 0 && hasOwn(strengths, o.strength)
      : hasOwn(drinks, o.drink) && hasOwn(styles, o.style) && list(o.flavors, flavors)));
    if (!value || !validSeed ||
      !Array.isArray(value.ratings) || value.ratings.length > 2000 ||
      !value.ratings.every(r => r && text(r.recipeID) && text(r.name) && ["like","okay","dislike"].includes(r.value) &&
        vectorValid(r.vector) && text(r.base) && text(r.family) && list(r.feedback, feedback) &&
        !(r.feedback.includes("strong") && r.feedback.includes("weak")) &&
        typeof r.updatedAt === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(r.updatedAt) && Number.isFinite(Date.parse(r.updatedAt))) ||
      new Set(value.ratings.map(r => r.recipeID)).size !== value.ratings.length) throw new Error("口味档案格式不正确。");
    return { onboarding: o ? (paletteMode ? { palette: [...o.palette], strength: o.strength } : { drink: o.drink, style: o.style, flavors: [...o.flavors] }) : null,
      ratings: value.ratings.map(r => ({ recipeID:r.recipeID, name:r.name, value:r.value, vector:[...r.vector], base:r.base, family:r.family, feedback:[...r.feedback], updatedAt:r.updatedAt })) };
  }
  function initial(answers) {
    if (!answers) return [...neutral];
    if (answers.palette) {
      const vector = neutral.map((n,i) => Math.round((n + answers.palette.reduce((sum,key) => sum + palette[key][2][i], 0)) / (answers.palette.length + 1)));
      vector[3] = strengths[answers.strength][1];
      return vector;
    }
    const vector = drinks[answers.drink][1].map((v,i) => (v + styles[answers.style][1][i]) / 2);
    const selected = new Set(answers.flavors.map(k => flavors[k][1]));
    for (const i of selected) vector[i] = clamp(vector[i] + 12);
    return vector.map(Math.round);
  }
  function amount(raw) {
    const match = raw.match(/(\d+(?:\.\d+)?)(?:\s*(?:到|[-–])\s*(\d+(?:\.\d+)?))?\s*(ml|毫升|cl|oz|g|克)/i);
    if (match) return (Number(match[1]) + Number(match[2] || match[1])) / 2 * ({cl:10,oz:30,g:1.5,"克":1.5}[match[3].toLowerCase()] || 1);
    if (/补满/.test(raw)) return 90;
    if (/苦精|苦艾|橙花水|盐|胡椒|辣椒/.test(raw)) return 3;
    if (/薄荷|柠檬皮/.test(raw)) return 8;
    if (/糖/.test(raw)) return 10;
    return 20;
  }
  function profile(recipe) {
    const parts = (recipe.parts || recipe.ingredients.map(BarCore.ingredient)).filter(p => !p.optional && !p.substitution);
    const vectors = [], bases = Object.create(null), unknown = [];
    for (const part of parts) {
      const name = BarCore.canonical(part.types[0]);
      const data = hasOwn(BarTasteData, name) ? BarTasteData[name] : null;
      if (!data) { unknown.push(name); continue; }
      if (/碎冰|盐|柠檬片|青柠片|柠檬皮/.test(name)) continue;
      const volume = amount(part.raw);
      vectors.push({ ...data, volume });
      if (data.base) bases[data.base] = (bases[data.base] || 0) + volume;
    }
    const volume = vectors.reduce((sum,v) => sum + v.volume, 0) || 1;
    // Acidity is perceptible at low juice ratios; body should not be amplified
    // like aroma. These are editorial response curves, not chemical measurements.
    const scale = [1.8, 1, 1.55, 0.9, 1.65, 1.3, 1.6, 1];
    const vector = neutral.map((_,i) => {
      const average = vectors.reduce((sum,v) => sum+v.vector[i]*v.volume,0)/volume;
      return Math.round(clamp(i===1 ? 100*(1-Math.exp(-average/28)) : average*scale[i]));
    });
    const names = parts.map(p=>p.types.join(" ")).join(" ");
    if (/薄荷/.test(names)) vector[5] = Math.max(60, vector[5]);
    const family = /热饮|热咖啡/.test(recipe.method) ? "热饮系"
      : /奶油|牛奶|百利甜|椰浆|可可/.test(names) ? "奶香甜点系"
      : /金巴利|阿佩罗/.test(names) ? "苦甜开胃系"
      : /苏打|汤力|汽水|可乐|姜汁|香槟|普洛赛克/.test(names) ? "清爽长饮系"
      : /柠檬汁|青柠/.test(names) ? "酸甜系 Sour"
      : vector[4] >= 45 && vector[3] < 55 ? "果香系"
      : vector[3] < 10 ? "轻盈调和系" : "经典烈酒系";
    return { vector, family, base:Object.entries(bases).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0] || "无基酒", unknown,
      estimated:true, approximate:parts.some(p=>/补满|到|少量|适量/.test(p.raw)) };
  }
  const distance = (a,b) => Math.sqrt(a.reduce((sum,v,i)=>sum+weights[i]*(v-b[i])**2,0)/weights.reduce((a,b)=>a+b,0));
  const score = (a,b) => Math.round(clamp(100-distance(a,b)));
  const strength = vector => vector[3] < 35 ? "轻柔" : vector[3] < 65 ? "适中" : "浓烈";
  function characteristics(vector) {
    return vector.map((v,i)=>({v,i})).filter(x=>x.i!==3 && x.v>=45).sort((a,b)=>b.v-a.v||a.i-b.i).slice(0,3).map(x=>dimensions[x.i]);
  }
  function describe(vector) {
    const names = characteristics(vector);
    return `${names.length ? `${names.join("、")}更突出` : "风味较轻盈"}，酒感${strength(vector)}。`;
  }
  function dna(taste = empty()) {
    const seed = initial(taste.onboarding), sums = seed.map(v=>v*5);
    const ratings = [...taste.ratings].sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt)||a.recipeID.localeCompare(b.recipeID));
    let total = 5;
    const bases = Object.create(null), families = Object.create(null);
    ratings.forEach((r,index)=>{
      const recent = 0.5 + 0.5 * 2 ** (-(ratings.length-1-index)/12);
      const weight = recent * ({like:1,okay:0.5,dislike:0.75}[r.value]);
      const target = r.vector.map((v,i)=>r.value === "dislike" ? clamp(seed[i]+(seed[i]-v)*0.5) : r.value === "okay" ? (seed[i]+v)/2 : v);
      for (const key of r.feedback) {
        const [,i,delta]=feedback[key]; target[i]=clamp(r.vector[i]+delta);
      }
      target.forEach((v,i)=>{ sums[i]+=v*weight; }); total+=weight;
      if(r.value==="like") {
        bases[r.base]=(bases[r.base]||0)+recent;
        families[r.family]=(families[r.family]||0)+recent;
      }
    });
    const favourite = values => Object.entries(values).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0] || "等待喜欢的记录";
    const vector=sums.map(v=>Math.round(v/total));
    return { vector, ready:!!taste.onboarding||ratings.length>0, count:ratings.length,
      stage:ratings.length<3?"DNA 起步":ratings.length<10?"DNA 形成中":"DNA 逐渐清晰",
      evidence:ratings.length<3?"目前只是初步线索，匹配仅供探索。":ratings.length<10?"正在结合你的真实反馈调整。":"已积累一些偏好线索，口味仍会变化。",
      base:favourite(bases), family:favourite(families), explored:new Set(ratings.map(r=>r.family)).size,
      description:describe(vector) };
  }
  function explain(profile, user) {
    if (!user.ready) return "选择喜欢的风味，或评价喝过的酒。";
    if(profile.unknown.length) return "部分材料尚无风味数据，暂不计算匹配度。";
    const closest=profile.vector.map((v,i)=>({i,d:Math.abs(v-user.vector[i])})).filter(x=>user.vector[x.i]>=30 || profile.vector[x.i]>=30).sort((a,b)=>a.d-b.d||a.i-b.i).slice(0,2);
    const different=profile.vector.map((v,i)=>({i,d:v-user.vector[i]})).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d)||a.i-b.i)[0];
    return `${closest.length?`${closest.map(x=>dimensions[x.i]).join("、")}接近你的偏好`:"整体风味较轻盈"}${Math.abs(different.d)>=15?`；${dimensions[different.i]}${different.d>0?"更突出":"更轻"}`:"，整体风格相近"}。`;
  }
  function recommend(recipes, taste, user=dna(taste)) {
    if(!user.ready) return [];
    const disliked=new Set(taste.ratings.filter(r=>r.value==="dislike").map(r=>r.recipeID));
    const ranked=recipes.map(r=>({recipe:r,profile:profile(r)})).filter(x=>!x.profile.unknown.length&&!disliked.has(x.recipe.id))
      .map(x=>({...x,score:score(x.profile.vector,user.vector)})).sort((a,b)=>b.score-a.score||a.recipe.id.localeCompare(b.recipe.id));
    return [
      { title:"贴合你的口味", subtitle:"从熟悉的味道开始", items:ranked.filter(x=>x.score>=75).slice(0,3) },
      { title:"换一点新口味", subtitle:"保留相似之处，尝试一点变化", items:ranked.filter(x=>x.score>=65&&x.score<85).slice(0,3) },
      { title:"喜欢的家族", subtitle:user.family, items:ranked.filter(x=>x.profile.family===user.family).slice(0,3) },
      { title:"走出熟悉口味", subtitle:"差异适中，先看看哪里不同", items:ranked.filter(x=>x.score>=45&&x.score<65).slice(0,3) },
    ];
  }
  globalThis.BarTaste={dimensions,drinks,styles,flavors,palette,strengths,feedback,empty,validate,initial,profile,dna,score,distance,strength,characteristics,describe,explain,recommend};
})();

BarTaste = globalThis.BarTaste;
/* Presentation-only localization. Canonical ingredient IDs and saved user text
   stay in their original language. No network translation or DOM observer. */
(() => {
  let locale = 'zh-CN';
  const messages = Object.create(null);
  let matcher;
  const han = /[\u3400-\u9fff]/;
  function add(entries) {
    Object.assign(messages, entries);
    matcher = null;
  }
  function setLocale(value) {
    locale = value === 'en' ? 'en' : 'zh-CN';
    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale;
      document.title = locale === 'en' ? 'drinkdrinkdrunk' : '大喝特喝';
      document.querySelector('#modal')?.setAttribute('aria-label', t('编辑内容'));
    }
  }
  function t(value) {
    const source = String(value ?? '');
    if (locale !== 'en' || !han.test(source)) return source;
    const trimmed = source.trim();
    if (hasOwn(messages, trimmed)) return source.replace(trimmed, messages[trimmed]);
    const step = trimmed.match(/^(可选：)?将 (.+) 加入(.+)。$/);
    if (step) return `${step[1] ? 'Optional: ' : ''}Add ${t(step[2])} to the ${t(step[3]).toLowerCase()}.`;
    const about = trimmed.match(/^(\d+) 款配方，含 (\d+) 款 IBA 精选。$/);
    if (about) return `${about[1]} recipes, including ${about[2]} IBA selections.`;
    const missing = trimmed.match(/^缺 (\d+) 项 · (.+)$/);
    if (missing) return `Missing ${missing[1]}: ${t(missing[2])}`;
    const flavor = trimmed.match(/^(.+)更突出，酒感(.+)。$/);
    if (flavor) return `Prominent notes: ${t(flavor[1])}. ${t(flavor[2])} strength.`;
    const light = trimmed.match(/^风味较轻盈，酒感(.+)。$/);
    if (light) return `Light flavors, with ${t(light[1]).toLowerCase()} strength.`;
    // Longest phrases first: quantities and punctuation remain intact.
    matcher ||= new RegExp(Object.keys(messages).filter(Boolean).sort((a,b)=>b.length-a.length)
      .map(s=>s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|'), 'g');
    return source.replace(matcher, s => messages[s])
      .replace(/，|、/g, ', ').replace(/。/g, '. ').replace(/；/g, '; ')
      .replace(/：/g, ': ').replace(/（/g, ' (').replace(/）/g, ')')
      .replace(/「|」|“|”/g, '"').replace(/？/g, '?');
  }
  function html(source) {
    if (locale !== 'en' || !han.test(source)) return source;
    const template = document.createElement('template');
    template.innerHTML = source;
    function visit(node) {
      if (node.nodeType === 3) { node.textContent = t(node.textContent); return; }
      if (node.nodeType === 1) {
        if (node.matches('[translate="no"],script,style')) return;
        // An option without an explicit value uses its label as its data value.
        if (node.tagName === 'OPTION' && !node.hasAttribute('value')) node.value = node.textContent;
        for (const attr of ['aria-label','aria-description','aria-valuetext','title','alt','placeholder','label']) {
          if (node.hasAttribute(attr)) node.setAttribute(attr, t(node.getAttribute(attr)));
        }
        if (node.tagName === 'TEXTAREA') return;
      }
      [...node.childNodes].forEach(visit);
    }
    visit(template.content);
    return template.innerHTML;
  }
  function name(recipe) {
    return locale === 'en' ? recipe.englishName || recipe.chineseName : recipe.chineseName;
  }
  function savedName(record, recipes = globalThis.BarData?.recipes || []) {
    const recipe = recipes.find(r => r.id === record.recipeID);
    return recipe && [recipe.chineseName, recipe.englishName].includes(record.name) ? name(recipe) : record.name;
  }
  function recipeText(recipe, value) { return recipe.isUserCreated ? String(value ?? '') : t(value); }
  function canonicalIngredient(value) {
    const lower = value.toLowerCase();
    return globalThis.BarData?.catalog.find(item => String(messages[item.name] || item.name.replace(/[\u3400-\u9fff]+/g, part => messages[part] || part)).toLowerCase() === lower)?.name || value;
  }
  function month(value) {
    const [y,m] = value.split('-').map(Number);
    const d = new Date(0); d.setFullYear(y,m-1,1);
    return new Intl.DateTimeFormat(locale, {year:'numeric',month:'long'}).format(d);
  }
  function day(value) {
    const [y,m,d] = value.split('-').map(Number);
    const date = new Date(0); date.setFullYear(y,m-1,d);
    return new Intl.DateTimeFormat(locale, {month:'long',day:'numeric'}).format(date);
  }
  globalThis.BarI18n = { add, t, html, setLocale, name, savedName, recipeText, month, day, canonicalIngredient,
    get locale() { return locale; }, get messages() { return {...messages}; },
    get weekdays() { return locale === 'en' ? ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] : ['一','二','三','四','五','六','日']; } };
})();

BarI18n = globalThis.BarI18n;
(() => {
  const escape = (value) =>
    String(value ?? "").replace(
      /[&<>"']/g,
      (c) =>
        ({
          "&": "&amp;",
          "<": "&lt;",
          ">": "&gt;",
          '"': "&quot;",
          "'": "&#39;",
        })[c],
    );
  function bottle(item = {}) {
    const color = /^#[a-f\d]{6}$/i.test(item.color) ? item.color : "#79a883";
    const paths = {
      bottle:
        "M42 15H62V49Q62 56 76 67V145Q76 153 68 153H36Q28 153 28 145V67Q42 56 42 49Z",
      round: "M43 18H61V55C98 69 96 150 66 153H38C8 150 6 69 43 55Z",
      carton: "M28 41L40 18H69L82 41V153H28Z",
      jar: "M25 49Q25 40 35 40H72Q82 40 82 49V145Q82 153 72 153H35Q25 153 25 145Z",
      whiskey: 'M43 18H65V51L83 64V145Q83 153 75 153H33Q25 153 25 145V64L43 51Z',
      gin: 'M44 17H64V45Q64 49 83 57V147L75 153H33L25 147V57Q44 49 44 45Z',
      vodka: 'M43 17H65V42C65 53 81 53 81 73V145Q81 153 72 153H36Q27 153 27 145V73C27 53 43 53 43 42Z',
      tequila: 'M44 44H65V63Q87 67 88 85V137Q87 153 69 153H40Q21 153 21 137V85Q22 67 44 63Z',
      rum: 'M46 14H62V66Q76 69 76 82V146Q76 153 67 153H41Q32 153 32 146V82Q32 69 46 66Z',
    };
    const necks = { bottle: [42, 20], round: [43, 18], whiskey: [43, 22], gin: [44, 20], vodka: [43, 22], rum: [46, 16] };
    const highlights = {
      bottle: 'M35 74V139', round: 'M25 79Q15 108 27 137',
      carton: 'M35 51V139', jar: 'M31 55V139', whiskey: 'M32 73V139',
      gin: 'M32 66V139', vodka: 'M34 75V139',
      tequila: 'M30 81Q27 86 28 98V136', rum: 'M40 83V140',
    };
    const [neckX, neckWidth] = necks[item.shape] || necks.bottle;
    const cap = item.shape === 'carton'
      ? '<path d="M40 18H69M28 41H82M40 18L52 41L69 18" fill="none" stroke="#fff8e8" stroke-width="3"/>'
      : item.shape === 'jar' ? '<rect data-cap="jar" x="25" y="34" width="57" height="13" rx="4" fill="#ba9560" stroke="#29494d" stroke-width="2"/><path d="M30 39H77" stroke="#e6c892"/>'
      : item.shape === 'tequila' ? '<rect x="41" y="32" width="27" height="17" rx="4" fill="#ba895b" stroke="#765336" stroke-width="2"/>'
      : `<rect data-cap="bottle" x="${neckX - 3}" y="10" width="${neckWidth + 6}" height="14" rx="3" fill="#29494d"/><path d="M${neckX + 2} 15H${neckX + neckWidth - 2}" stroke="#c7a268" stroke-width="2"/>`;
    const strokes = (item.drawing || [])
      .map(
        (points) =>
          `<polyline points="${points.map((p) => p.map(Number).join(",")).join(" ")}"/>`,
      )
      .join("");
    return `<svg viewBox="0 0 110 170" aria-hidden="true" data-bottle="${escape(item.shape || 'bottle')}"><ellipse cx="55" cy="159" rx="34" ry="5" fill="#203d3d" opacity=".1"/><path d="${paths[item.shape] || paths.bottle}" fill="${color}" stroke="#29494d" stroke-width="2.5"/>${reflection(paths[item.shape] || paths.bottle, highlights[item.shape] || highlights.bottle, 2.5, .25)}${cap}<rect x="32" y="83" width="45" height="41" rx="${item.shape === 'whiskey' ? 1 : 8}" fill="${item.shape === 'whiskey' ? '#293b3b' : '#fff8e8'}" stroke="#d3b982"/><path d="M43 100H65M47 107H61" stroke="${item.shape === 'whiskey' ? '#ecd7ae' : '#29494d'}" opacity=".7" stroke-width="2"/><g fill="none" stroke="#29494d" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" transform="translate(14 40) scale(.42)">${strokes}</g></svg>`;
  }
  const glassShapes = {
    hurricane: { path: 'M48 20H112Q88 66 111 102Q125 144 80 147Q35 144 49 102Q72 66 48 20Z', rim:20, bottom:147, left:48, right:112, cubes:[[69,122,22,-10],[91,119,22,9],[80,88,21,-7]] },
    mug: { path:'M35 40H115V156Q115 167 103 167H47Q35 167 35 156Z',rim:40,bottom:167,left:35,right:115,cubes:[[59,142,24,-10],[93,140,24,10]] },
    shot: { path:'M48 79H112L104 167H56Z',rim:79,bottom:167,left:48,right:112,cubes:[[80,143,20,0]] },
    margarita: { path:'M17 44H143Q139 80 103 83Q105 119 80 122Q55 119 57 83Q21 80 17 44Z',rim:44,bottom:122,left:17,right:143,cubes:[[78,97,22,12],[52,62,22,-9],[107,62,22,8]] },
    bowl: { path:'M17 72H143Q137 165 80 165Q23 165 17 72Z',rim:72,bottom:165,left:17,right:143,cubes:[[58,135,26,12],[99,131,26,-10],[78,105,24,0]] },
    coupe: { path: "M22 48H138Q130 110 80 111Q30 110 22 48Z", rim: 48, bottom: 111, left: 22, right: 138, cubes: [[61,83,21,-12],[91,84,23,14],[77,64,20,-5]] },
    martini: { path: "M15 42H145L80 118Z", rim: 42, bottom: 118, left: 15, right: 145, cubes: [[79,91,18,8],[57,61,22,-12],[99,60,22,16]] },
    highball: { path: "M43 18H117L110 167H50Z", rim: 18, bottom: 167, left: 43, right: 117, cubes: [[65,148,23,-8],[94,146,24,10],[79,118,25,-12]] },
    rocks: { path: "M29 76H131L124 167H36Z", rim: 76, bottom: 167, left: 29, right: 131, cubes: [[61,145,28,-12],[100,143,28,12],[80,111,27,-8]] },
    wine: { path: "M39 25H121Q149 113 80 115Q11 113 39 25Z", rim: 25, bottom: 115, left: 39, right: 121, cubes: [[62,87,24,-14],[94,87,25,12],[79,57,24,-8]] },
  };
  const vesselShape = { path: "M40 62H120L108 172H52Z", rim: 62, bottom: 172, left: 40, right: 120, cubes: [[70,147,25,-10],[94,120,24,12],[68,93,25,-8]] };
  // Follow each glass wall, inset from its outline. Curved bowls need curved
  // reflections; a shared fixed slope can put the stroke outside a martini glass.
  const glassHighlights = {
    hurricane: 'M58 35Q66 53 64 70', mug: 'M42 54V84',
    shot: 'M55 91L57 113', margarita: 'M26 55Q31 72 48 76',
    bowl: 'M26 84Q29 108 40 126', coupe: 'M32 60Q37 82 51 91',
    martini: 'M33 54L47 70.4', highball: 'M50 32L51.7 68',
    rocks: 'M37 89L39.3 119', wine: 'M44 40Q36 65 41 82',
  };
  let drawingID = 0;
  function reflection(outline, path, width = 2.2, opacity = .4) {
    const id = `reflection-${++drawingID}`;
    return `<defs><clipPath id="${id}"><path d="${outline}"/></clipPath></defs><path data-reflection="true" d="${path}" fill="none" stroke="white" stroke-width="${width}" stroke-linecap="round" opacity="${opacity}" clip-path="url(#${id})"/>`;
  }
  function contents(shape, color, options) {
    const id = `drink-contents-${++drawingID}`;
    const level = Math.max(0, Math.min(0.9, options.level ?? 0.7));
    const surface = shape.bottom - (shape.bottom - shape.rim) * level;
    const layers = options.layers;
    const gradient = layers ? `<linearGradient id="${id}-gradient" x1="0" y1="${surface}" x2="0" y2="${shape.bottom}" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="${layers[0]}"/><stop offset=".38" stop-color="${layers[0]}"/><stop offset=".72" stop-color="${layers[1]}"/><stop offset="1" stop-color="${layers[1]}"/></linearGradient>` : '';
    return `<defs>${gradient}<clipPath id="${id}"><path d="${shape.path}"/></clipPath><clipPath id="${id}-ice"><path d="${shape.path}"/><rect x="${shape.left}" y="-140" width="${shape.right-shape.left}" height="${shape.rim+140}"/></clipPath></defs>
      <g clip-path="url(#${id})" class="drink-liquid" fill="${color}">${level ? `<rect x="0" y="${surface}" width="160" height="${shape.bottom-surface}" fill="${layers ? `url(#${id}-gradient)` : color}" fill-opacity=".85"/><ellipse cx="80" cy="${surface}" rx="70" ry="3" fill-opacity=".3"/>${options.foam ? `<rect x="0" y="${surface}" width="160" height="7" fill="#fff4db" opacity=".9"/>` : ''}` : ""}</g>
      <g clip-path="url(#${id}-ice)" class="drink-ice">${options.ice ? shape.cubes.map(([x,y,size,angle], i) => `<g transform="translate(${x} ${y}) rotate(${angle})"><g class="ice-piece ${options.animateIce ? "ice-falling" : ""}" style="--ice-start:${shape.rim-y-70}px;--ice-delay:${i*0.32}s"><rect x="${-size/2}" y="${-size/2}" width="${size}" height="${size}" rx="5" fill="#dceff2" fill-opacity=".8" stroke="#7ca5b0" stroke-width="1.3"/><path d="M${-size/2+4} ${size/2-5}V${-size/2+5}H${size/2-5}" fill="none" stroke="white" stroke-opacity=".9" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M${-size/2+4} ${size/2-4}L${size/2-4} ${-size/2+4}V${size/2-4}Z" fill="#92bfca" fill-opacity=".23"/></g></g>`).join("") : ""}</g>`;
  }
  function glass(kind = "coupe", color = "#da9561", options = {}) {
    color = /^#[a-f\d]{6}$/i.test(color) ? color : "#da9561";
    const shape = glassShapes[kind] || glassShapes.coupe;
    const stem = ["highball", "rocks", "mug", "shot", "bowl"].includes(kind)
      ? ""
      : `<path d="M80 ${shape.bottom}V170M52 174H108" fill="none" stroke="#31535a" stroke-width="4" stroke-linecap="round"/>`;
    return `<svg viewBox="0 0 160 190" aria-hidden="true" data-glass="${escape(kind)}"><ellipse cx="80" cy="181" rx="46" ry="5" fill="#203d3d" opacity=".09"/><path d="${shape.path}" fill="#e2eff0" fill-opacity=".23"/>${contents(shape, color, options)}<path d="${shape.path}" fill="none" stroke="#31535a" stroke-width="3" stroke-linejoin="round"/>${reflection(shape.path, glassHighlights[kind] || glassHighlights.coupe)}${stem}${kind === "mug" ? '<path d="M115 66Q151 63 146 105Q145 130 115 130" fill="none" stroke="#31535a" stroke-width="5"/>' : ""}${garnish(options.garnish, shape)}</svg>`;
  }
  function garnish(type, shape) {
    if (type === false || type === 'none') return '';
    const x = shape.right - 5, y = shape.rim + 4;
    if (type === 'mint') return `<g transform="translate(${x} ${y})"><path d="M0 18Q-31 -14 -12 -18Q1 -15 0 18Q1 -20 18 -20Q31 -2 0 18" fill="#5b975d" stroke="#366b45" stroke-width="2"/></g>`;
    if (type === 'coffee') return '<g fill="#503526"><ellipse cx="66" cy="67" rx="5" ry="3"/><ellipse cx="80" cy="71" rx="5" ry="3"/><ellipse cx="90" cy="63" rx="5" ry="3"/></g>';
    if (type === 'olive') return `<path d="M65 ${y+40}L132 ${y-10}" stroke="#ab8753" stroke-width="2"/><ellipse cx="92" cy="${y+20}" rx="11" ry="8" fill="#929b55"/><circle cx="98" cy="${y+18}" r="3" fill="#bc6754"/>`;
    const color = type === 'orange' ? '#f3ac4e' : type === 'lemon' ? '#e8d772' : '#bed183';
    return `<g transform="translate(${x} ${y})"><circle r="17" fill="${color}" stroke="#8c9250" stroke-width="2"/><circle r="13" fill="none" stroke="#fff1bd"/><path d="M-13 0H13M0 -13V13M-9 -9L9 9M-9 9L9 -9" stroke="#fff1bd" stroke-width="1.5"/></g>`;
  }
  function drink(recipe) {
    const look = BarCore.drinkAppearance(recipe);
    return glass(look.glass, look.color, look.visual || {});
  }
  function vessel(kind, options = {}) {
    const lid = kind === "shaker"
      ? '<g class="vessel-lid"><path d="M42 62L57 35H103L118 62Z" fill="#dae3dc" stroke="#31535a" stroke-width="3"/><rect x="62" y="18" width="36" height="18" rx="5" fill="#31535a"/></g>'
      : '<ellipse cx="80" cy="62" rx="40" ry="7" fill="#dfe9df" stroke="#31535a" stroke-width="3"/>';
    const blender = kind === "blender" ? '<path d="M120 80Q151 82 140 128L114 136" fill="none" stroke="#31535a" stroke-width="6"/><rect x="45" y="155" width="70" height="22" rx="5" fill="#31535a"/><circle cx="80" cy="166" r="5" fill="#e0b788"/>' : '';
    const color = /^#[a-f\d]{6}$/i.test(options.color) ? options.color : "#d69867";
    return `<svg viewBox="0 0 160 190" aria-hidden="true" data-vessel="${escape(kind)}"><ellipse cx="80" cy="181" rx="46" ry="5" fill="#203d3d" opacity=".09"/><path d="${vesselShape.path}" fill="#b7c8c3" fill-opacity=".4"/>${contents(vesselShape, color, options)}<path d="${vesselShape.path}" fill="none" stroke="#31535a" stroke-width="3"/>${lid}${reflection(vesselShape.path, 'M49 79L54 125', 2.5, .35)}${blender}</svg>`;
  }
  const rim = (kind) => (glassShapes[kind] || vesselShape).rim;
  globalThis.BarArt = { escape, bottle, glass, vessel, rim, drink };
})();

BarArt = globalThis.BarArt;

/* Chinese source phrases are stable message keys. Keep longer, contextual
   translations here rather than translating canonical application data. */
BarI18n.add(Object.fromEntries(`
大喝特喝|drinkdrinkdrunk
语言|Language
酸爽|Bright & tart
长饮|Long drink
世界经典|World classic
利口酒|Liqueur
开胃酒|Aperitif
起泡|Sparkling
IBA 精选|IBA selection
IBA · 官方配方与教程|IBA · Official recipe & guide
摇和|Shaken
分层|Layered
直接调和|Built
果味利口酒|Fruit liqueur
花香利口酒|Floral liqueur
甜点利口酒|Dessert liqueur
葡萄酒|Wine
无法导出这张图片。|Could not export this image.
图片无效或窗口不可用。|The image is invalid or the window is unavailable.
请稍后重试。|Please try again shortly.
图片分享失败，请重试。|Could not share the image. Try again.
的配方与风味分享卡片| recipe and flavor card
日记| journal
评价| rating
选择界面语言，立即生效并保存在本机。|Choose your language. Changes apply immediately and are saved on this device.
设置与数据|Settings & data
设置与数据备份 ↗|Settings & backup ↗
设置与备份|Settings & backup
显示外观|Appearance
主题|Theme
深夜酒吧|Late-night bar
日间|Daylight
低光|Low light
备份与迁移|Backup & transfer
导出备份|Export backup
导入备份|Import backup
新手引导|Getting started
重新查看新手引导|Replay the tour
关于|About
重播开场动画|Replay the opening
开灯营业，欢迎回来。开启系统“减少动态效果”时自动跳过。|Lights on. Welcome back. Skipped automatically when Reduce Motion is enabled.
发现配方|Discover
我的吧台|My bar
我的收藏|Favorites
饮酒日记|Drink journal
口味 DNA|Taste DNA
你的居家调酒手册|Your home cocktail companion
主要导航|Main navigation
＋ 自建配方|＋ Add recipe
请适量饮用 · 饮酒后勿驾驶|Drink responsibly · Never drink and drive
未找到这个配方|Recipe not found
返回配方库|Back to recipes
已加入饮酒日记。|Added to your drink journal.
配方库|Recipe library
配方列表|Recipes
全部配方|All recipes
不限|Any
缺 0 项|Nothing missing
最多缺 1 项|Missing up to 1
最多缺 2 项|Missing up to 2
整理我的吧台|Organize my bar
款配方| recipes
件吧台材料| bar ingredients
款收藏| favorites
搜索酒名、基酒、材料…|Search drinks, spirits, ingredients…
搜索配方|Search recipes
基酒筛选|Filter by spirit
我的配方|My recipes
动画跟做|Guided mixing
新增 IBA 精选|IBA selection
按我的材料找酒|Find drinks I can make
我的口味 DNA ↗|My taste DNA ↗
风味调色盘|Flavor palette
配方排序|Sort recipes
按我的口味匹配|Taste match
原有顺序|Original order
比较两杯 ↗|Compare drinks ↗
取消收藏|Unfavorite
收藏|Favorite
收藏夹还在等第一杯|Your first favorite is waiting
还没有找到合适的配方|No matching recipes yet
重置筛选|Reset filters
旧记录 · 请补选标准类型|Imported items · Choose ingredient types
待选择类型|Choose a type
暂无材料|Your bar is empty
登记第一件材料|Add your first ingredient
＋ 登记材料|＋ Add ingredient
件材料 ·| ingredients ·
种标准类型| ingredient types
看看能调什么 ↗|See what I can mix ↗
尚未选择检查类别|Choose categories to check
所列必需材料齐全|All required ingredients available
所检查材料齐全|All checked ingredients available
所列必需材料缺|Required ingredients missing:\u0020
替代方案|Alternative
可选|Optional
已有|Available
缺少|Missing
♥ 已收藏|♥ Saved
♡ 收藏|♡ Favorite
删除自建配方|Delete my recipe
← 回到配方库|← Back to recipes
配料|Ingredients
做法|Method
▶ 开始跟做|▶ Start mixing
分享卡片|Share card
记一杯|Log a drink
关闭|Close
编辑内容|Edit content
编辑材料|Edit ingredient
登记一件材料|Add an ingredient
容器造型|Bottle shape
移除材料|Remove ingredient
展示名称|Display name
标准材料类型|Ingredient type
请选择标准类型|Choose an ingredient type
例如：我的蓝瓶酒|e.g. My blue bottle
容器颜色|Bottle color
亲手画外观 · 标签与瓶身涂鸦|Draw your own label & bottle art
撤销一笔|Undo stroke
清空画板|Clear drawing
材料外观画板|Bottle drawing canvas
取消|Cancel
保存材料|Save ingredient
材料已保存，配方匹配已更新。|Ingredient saved. Recipe matches updated.
记录你的配方|Create your recipe
中文名称|Recipe name
英文名称（可留空）|English name (optional)
材料与用量（每行一项）|Ingredients & amounts (one per line)
主色|Main color
保存配方|Save recipe
暂无记录|No entries
旧日记未记录外观|No appearance saved for this older entry
未记录外观|No appearance saved
未填写备注|No notes yet
的照片| photo
编辑|Edit
补充备注|Add notes
删除|Delete
这一天还没有记录|No drinks logged on this day
＋ 记一杯|＋ Log a drink
饮酒日记月历|Drink journal calendar
本月|This month:\u0020
条记录| entries
上个月|Previous month
今天|Today
下个月|Next month
编辑日记|Edit journal entry
添加日记|Add journal entry
外观|Appearance
当前外观|Current look
纯色|Solid color
酒液颜色|Drink color
日期|Date
酒名|Drink name
今天的感受|Your thoughts
口味、用量调整或其他备注|Flavor, recipe tweaks or other notes
这一杯的照片|Photos of this drink
最多 3 张，每张原图不超过 12 MB。仅在本机压缩保存，备份包含照片，不保留原图。|Up to 3 photos, 12 MB each. Compressed on this device and included in backups. Originals are not stored.
保存日记|Save entry
下载日记照片|Download journal photo
日记照片|Journal photo
移除照片|Remove photo
下载 JSON|Download JSON
导出吧台备份|Export your bar
复制下面内容，在另一台设备的“导入备份”中粘贴。|Copy the content below and paste it into Import backup on another device.
备份内容|Backup content
选择并复制|Select & copy
已复制备份。|Backup copied.
已选中，请使用系统复制操作。|Selected. Use your device's Copy command.
导入吧台备份|Import your bar
导入会替换当前新吧台数据，请先导出当前备份。|Importing replaces your current bar data. Export a backup first.
选择备份文件|Choose a backup file
或粘贴备份内容|Or paste backup content
我已备份当前数据，确认替换|I have backed up my data and agree to replace it
确认导入|Import & replace
文件超过 4 MB。|File exceeds 4 MB.
备份已导入。|Backup imported.
JSON 格式不正确，请检查完整内容。|Invalid JSON. Check that you copied the entire backup.
删除后可以通过先前导出的备份恢复。|You can restore deleted data from a previously exported backup.
确认删除|Delete
移除这件材料？|Remove this ingredient?
删除这个自建配方？|Delete this custom recipe?
删除这条日记？|Delete this journal entry?
已加入收藏。|Added to favorites.
已取消收藏。|Removed from favorites.
另一窗口的数据变动无法读取，请刷新后检查。|Could not read changes from another window. Refresh to check your data.
本地数据无法读取，已停止写入以保护原数据。请先导出原始数据，再导入有效备份。|Local data could not be read. Saving is disabled to protect it. Export the original data, then import a valid backup.
本地数据已接近容量上限，请先导出备份，再减少日记照片。原记录未更改。|Storage is nearly full. Export a backup, then remove some journal photos. Your entries are unchanged.
保存失败：存储空间不足或数据格式不正确。请先备份，内容尚未保存。|Could not save: storage is full or the data is invalid. Back up your data. Changes have not been saved.
量取与倒入|Measure & pour
加入冰块|Add ice
摇匀|Shake
搅拌|Stir
过滤入杯|Strain into the glass
倒入酒杯|Pour into the glass
补入饮料|Top up
装饰|Garnish
轻压|Muddle gently
搅打|Blend
漂浮分层|Float a layer
润洗酒杯|Rinse the glass
准备材料|Prepare ingredients
原方提示|Recipe instructions
摇壶|Shaker
调酒杯|Mixing glass
最终酒杯|Serving glass
搅拌机|Blender
备料区|Prep area
量酒器 / 备料碟|Jigger / prep dish
；此项可选|; optional
备好|Prepare\u0020
，先不要混合|; do not mix yet
按原配方选择|Follow the recipe
备料与原方引导|Prep & recipe guide
调制完成|Mixing complete
你的「|Your "
最终杯型|Serving glass
配方外观|Recipe look
这一杯，完成了。|Your drink is ready.
秒|seconds
接下来 ·|Next ·
最后一步 · 完成后记录这一杯|Last step · Log your finished drink
重新播放|Replay
Ⅱ 暂停|Ⅱ Pause
▶ 继续|▶ Resume
完成|Finish
下一步|Next
已加入饮酒日记|Added to journal
一键加入饮酒日记|Add to journal
已保持常亮|Screen stays awake
保持屏幕常亮|Keep screen awake
原方杯型|Recipe glass
退出跟做|Exit mixing
器具|Tool
目标|Target
上一步|Back
每步等待|Step interval
语音提示|Voice guidance
当前环境不支持常亮，可在系统设置中延长锁屏时间。|Keeping the screen awake is unavailable. Adjust your device's auto-lock setting.
喜欢|Like
还行|Okay
不喜欢|Dislike
第一组|First group
第二组|Second group
风味待完善|Flavor data incomplete
初步|Early estimate
口味匹配|taste match
尚未建立口味档案|No taste profile yet
轻盈柔和|Light and mellow
修改评价|Edit rating
评价这一杯|Rate this drink
与我的 DNA 对比|Compare with my DNA
未识别材料|Unknown ingredients
风味档案|Flavor profile
口味推荐|Recommendations
口味档案|Taste profile
查看我的 DNA ↗|View my DNA ↗
匹配|match
喜欢的家族|Favorite families
暂无喜欢的配方。|No liked recipes yet.
当前筛选下还没有这个范围的配方。|No recipes in this group match your filters.
调整风味|Adjust flavors
喜欢的基酒|Favorite spirit
偏好酒感|Preferred strength
已评价配方|Rated recipes
探索过的家族|Families explored
我的风味轮廓|My flavor profile
修改|Edit
撤销|Undo
暂无评价|No ratings yet
清除口味档案|Clear taste profile
我的口味 DNA|My taste DNA
我的口味记录|My taste history
已保存风味搭配。|Flavor preferences saved.
这款配方还有未识别的材料，风味数据完善后再评价。|This recipe has unknown ingredients. Rating will be available once its flavor data is complete.
评价 ·|Rate ·
你的整体感受|Your overall impression
具体反馈（可选）|Specific feedback (optional)
保存口味评价|Save rating
太烈和太淡，请选择更符合这次感受的一项。|Choose either too strong or too weak, whichever best describes this drink.
已更新你的口味 DNA。|Your taste DNA has been updated.
我的 DNA ↔|My DNA ↔
● 我的偏好|● My preferences
● 这杯的风味|● This drink
← 回到发现|← Back to Discover
比较两杯|Compare drinks
第一杯|First drink
第二杯|Second drink
查看配方 ↗|View recipe ↗
部分材料未识别。|Some ingredients are unknown.
已撤销评价，DNA 已重新计算。|Rating removed. DNA recalculated.
清除口味档案？|Clear your taste profile?
将移除风味调色盘与评价。库存、收藏和饮酒日记会保留。|This removes flavor preferences and ratings. Your bar, favorites and journal are kept.
清除口味数据|Clear taste data
酸香|Bright citrus
甜润果香|Sweet fruit
酸甜浆果|Tangy berries
清凉草本|Cool herbs
辛香|Warm spice
烘焙微苦|Roasted bitterness
柔滑奶香|Silky cream
浓郁可可|Rich cocoa
木质烟香|Wood & smoke
先看配方|Browse recipes first
风味预览|Flavor preview
喜欢的风味|Favorite flavors
保存搭配|Save preferences
尚未选择风味|No flavors selected
甜感|Sweetness
酸感|Acidity
苦感|Bitterness
酒感|Strength
果香|Fruit
草本|Herbal
烟熏|Smoke
醇厚|Body
清新柠檬水|Fresh lemonade
黑咖啡|Black coffee
热带果汁|Tropical juice
清爽|Refreshing
香甜|Sweet
浓烈|Bold
干爽|Dry
微苦|Bittersweet
莓果|Berries
椰子|Coconut
巧克力|Chocolate
轻柔|Light
适中|Balanced
太甜|Too sweet
太酸|Too sour
太苦|Too bitter
太烈|Too strong
太淡|Too weak
口味档案格式不正确。|Invalid taste profile.
热饮系|Hot drinks
奶香甜点系|Creamy & dessert
苦甜开胃系|Bittersweet aperitifs
清爽长饮系|Refreshing long drinks
酸甜系 Sour|Sours
果香系|Fruit-forward
轻盈调和系|Light blends
经典烈酒系|Spirit-forward classics
无基酒|No base spirit
更突出| stands out
风味较轻盈|Light flavors
等待喜欢的记录|Waiting for your first like
DNA 起步|DNA: first steps
DNA 形成中|DNA: taking shape
DNA 逐渐清晰|DNA: growing clearer
目前只是初步线索，匹配仅供探索。|These are early clues. Use matches as ideas to explore.
正在结合你的真实反馈调整。|Your ratings are helping refine this profile.
已积累一些偏好线索，口味仍会变化。|Your preferences are taking shape and may still change.
选择喜欢的风味，或评价喝过的酒。|Choose flavors you like or rate drinks you have tried.
部分材料尚无风味数据，暂不计算匹配度。|Some ingredients lack flavor data, so no match score is available yet.
接近你的偏好| is close to your preferences
整体风味较轻盈|A lighter overall flavor
更轻| is lighter
整体风格相近|a similar overall style
贴合你的口味|Close to your taste
从熟悉的味道开始|Start with familiar flavors
换一点新口味|Try a small twist
保留相似之处，尝试一点变化|Familiar notes with a little variation
走出熟悉口味|Explore something different
差异适中，先看看哪里不同|A moderate change — see what differs
酒类|Spirits & liqueurs
果汁|Juices
糖浆与糖|Syrups & sugars
饮料与乳品|Mixers & dairy
水果与其他|Fruit & extras
碟形杯|Coupe
马天尼杯|Martini glass
高球杯|Highball
古典杯|Rocks glass
葡萄酒杯|Wine glass
飓风杯|Hurricane glass
热饮杯|Hot-drink glass
烈酒杯|Shot glass
玛格丽特杯|Margarita glass
分享碗|Punch bowl
经典长瓶|Classic bottle
圆肚酒瓶|Round bottle
方肩威士忌瓶|Whiskey bottle
平肩金酒瓶|Gin bottle
圆肩伏特加瓶|Vodka bottle
矮身龙舌兰瓶|Tequila bottle
修长朗姆瓶|Rum bottle
果汁纸盒|Juice carton
糖浆罐|Syrup jar
这不是有效的吧台备份文件。|This is not a valid bar backup.
备份内容过大。|Backup is too large.
库存数据格式不正确。|Invalid inventory data.
配方数据格式不正确。|Invalid recipe data.
日记数据格式不正确。|Invalid journal data.
备份包含重复编号。|Backup contains duplicate IDs.
杯型|Glass
请选择 JPG、PNG 或 WebP 图片。|Choose a JPG, PNG or WebP image.
单张原图不能超过 12 MB。|Each original image must be under 12 MB.
这张图片压缩后仍太大，请选择较小的图片。|This image is still too large after compression. Choose a smaller one.
图片无法读取，请换一张有效图片。|Could not read this image. Choose a valid image.
每篇最多 3 张，请减少选择数量。|Up to 3 photos per entry. Select fewer images.
正在本地压缩照片…|Compressing photos on this device…
照片已准备好，保存日记后生效。|Photos ready. Save the entry to keep them.
跟随主题|App theme
与当前应用外观一致|Matches the current app theme
奶油吧台|Cream bar
奶油白 · 珊瑚橙|Cream · Coral
青柠气泡|Lime fizz
鼠尾草绿 · 青柠黄|Sage · Lime
落日橘调|Sunset orange
杏桃橘 · 暖沙色|Apricot · Warm sand
午夜海蓝|Midnight ocean
深海蓝 · 冰川青|Deep blue · Glacier teal
莓果奶昔|Berry shake
浅莓粉 · 玫瑰红|Berry pink · Rose
雾紫微醺|Violet haze
雾紫灰 · 鸢尾紫|Lavender gray · Iris
可可拿铁|Cocoa latte
燕麦米 · 可可棕|Oat · Cocoa
基酒待补充|Base spirit unknown
配方来源|Recipe source
配方文字过长，无法放入一张清晰的图片。请精简后重试。|This recipe is too long for one readable image. Shorten it and try again.
配方|Recipe
项材料| ingredients
风味待补充|Flavor data pending
轻盈 · 柔和|Light · Mellow
风味|Flavor
部分材料尚无风味数据|Some ingredients lack flavor data
酒杯插画加载超时，请重试。|Glass illustration timed out. Try again.
酒杯插画生成失败，请重试。|Could not draw the glass. Try again.
当前环境无法生成图片。|Image generation is unavailable in this environment.
图片生成失败，请重试。|Could not generate the image. Try again.
鸡尾酒|Cocktail
配方卡|Recipe card
默认|Default
保存／分享图片|Save / share image
保存图片|Save image
正在生成卡片…|Creating your card…
配色与边框|Colors & border
重新生成|Try again
系统分享|Share via device
主要风味|Main flavors
图片读取失败。|Could not read the image.
图片已保存。|Image saved.
已开始下载图片。|Image download started.
系统分享暂不可用，请保存图片后分享。|Device sharing is unavailable. Save the image to share it.
图片保存失败，请重试。|Could not save the image. Try again.
从你的吧台，开始第一杯|Your first drink starts here
登记材料，找到配方，跟着调制，再留下自己的口味记录。接下来一起认识这些入口。|Add your ingredients, find a recipe, mix along and record what you think. Let's find your way around.
先把家里的材料放上吧台|Stock your home bar
先登记家里的一瓶酒、一盒果汁或一罐糖浆。名称可以自己起，标准材料类型用于匹配配方。还可以选瓶型、换颜色，或在标签上画几笔。|Add a bottle, a carton of juice or a syrup. Give it your own name and choose an ingredient type for matching. Pick a bottle shape, change its color or draw on its label.
用已有材料找一杯酒|Find a drink with what you have
选择要检查的材料类别，再选缺 0 项、最多缺 1 项或最多缺 2 项。按所选材料检查，可选配料不计缺项；没勾选的类别不代表已经拥有。|Choose ingredient categories, then allow zero, one or two missing ingredients. Only selected categories are checked. Optional ingredients do not count; unchecked categories are not assumed to be stocked.
调制前，核对材料和用量|Check ingredients and amounts
详情会检查配方所列的全部必需材料，逐项标出缺少什么。冰块、方法中的装饰请另外备妥；做法和配方备注也在这里。|Recipe details check all required ingredients and highlight what is missing. Prepare ice and garnishes mentioned in the method separately. Instructions and notes are here too.
跟着步骤慢慢调|Mix one step at a time
开始跟做后可以暂停、回看上一步，或调整每步等待时间。也可以选杯型、开语音提示、保持屏幕常亮。调完后能一键加入饮酒日记。|Pause, revisit a step or adjust the interval. Choose a glass, enable voice guidance or keep the screen awake. When finished, add the drink to your journal.
调出自己的口味 DNA|Mix your own taste DNA
在“调整风味”里重新搭配。|Use Adjust flavors to change your preferences.\u0020
点选喜欢的味道，再点一次移除；选择酒感后保存。喝过之后还可以评价喜欢、还行或不喜欢，让后续推荐逐渐贴近你。|Tap flavors you like, and tap again to remove them. Choose a strength and save. Rate drinks Like, Okay or Dislike to help refine your recommendations.
把这一杯记下来|Remember this drink
点选日历中的日期，再点击“记一杯”，就能记录或补记当天喝的酒，添加照片和感受。有配方关联的记录，还可以直接留下口味评价。|Select a date and choose Log a drink to add an entry, photos and notes. Entries linked to a recipe also let you rate the drink.
收藏，也分享给朋友|Save and share your favorites
喜欢的配方可以收藏。点击“分享卡片”查看图片，默认配色跟随主题，也能换配色和边框，再保存图片；设备支持时还可打开系统分享。|Favorite recipes you like. Open Share card to preview an image matching your theme, or choose another color and border. Save the image or use device sharing when available.
也可以写下自己的配方|Write your own recipe
填入酒名、杯型、材料与用量和做法。材料每行一项，尽量使用标准材料名称，方便库存匹配和风味分析。自建配方也能查看、分享和按原方跟做。|Add a name, glass, ingredients, amounts and method. Use one ingredient per line and standard names for matching and flavor analysis. You can view, share and follow your own recipes too.
最后，记得备份你的吧台|Keep a backup of your bar
备份包含材料、收藏、自建配方、日记照片和口味档案，设备之间不会自动同步。导入会替换当前记录。以后想再看一遍，在设置里打开“新手引导”。|Backups include ingredients, favorites, recipes, journal photos and taste preferences. Devices do not sync automatically. Importing replaces current data. Replay this tour from Settings any time.
欢迎来到大喝特喝|Welcome to drinkdrinkdrunk
完成引导|Finish tour
开始引导|Start tour
跳过引导|Skip tour
营业中|WELCOME
灯亮了，吧台见。|Lights on. See you at the bar.
跳过开场动画|Skip opening animation
跳过|Skip
◌ 加载中|◌ Loading
Ⅱ 暂停音乐|Ⅱ Pause music
♫ 吧台音乐|♫ Bar music
暂停吧台音乐|Pause bar music
播放吧台音乐|Play bar music
After Hours · 电钢琴 / 低音 / 轻鼓 · 纯音乐|After Hours · Electric piano / bass / soft drums · Instrumental
音乐暂时无法播放，请点击重试。|Music is unavailable. Tap to try again.
音量|Volume
背景音乐音量|Background music volume
查看|View\u0020
款| drinks
类| families
件| items
项| items
缺|Missing\u0020
甜|Sweet
酸|Sour
苦|Bitter
香|Aroma
`.trim().split('\n').map(line => { const i=line.indexOf('|'); return [line.slice(0,i),line.slice(i+1)]; })));

/* Editorial English for built-in ingredients, methods and guided steps. */
BarI18n.add(Object.fromEntries(`
阿佩罗|Aperol
爱尔兰威士忌|Irish whiskey
安格仕苦精|Angostura bitters
白薄荷利口酒|White crème de menthe
白可可利口酒|White crème de cacao
白兰地|Brandy
白朗姆|White rum
百利甜|Baileys Irish cream
百香果糖浆|Passion fruit syrup
薄荷叶|Mint leaves
薄荷|Mint
冰红茶|Iced black tea
波本|Bourbon
菠萝汁|Pineapple juice
陈年朗姆|Aged rum
橙花水|Orange blossom water
橙味苦精|Orange bitters
橙味利口酒|Orange liqueur
橙汁|Orange juice
蛋白|Egg white
德梅拉拉糖浆|Demerara syrup
杜林标|Drambuie
番茄汁|Tomato juice
方糖|Sugar cube
费奈特|Fernet
蜂蜜姜糖浆|Honey-ginger syrup
蜂蜜糖浆|Honey syrup
伏特加|Vodka
覆盆子利口酒|Raspberry liqueur
覆盆子糖浆|Raspberry syrup
干白葡萄酒|Dry white wine
干味美思|Dry vermouth
干邑|Cognac
过量朗姆|Overproof rum
黑醋栗利口酒|Crème de cassis
黑朗姆|Dark rum
黑麦威士忌|Rye whiskey
黑麦|Rye whiskey
黑莓利口酒|Blackberry liqueur
黑樱桃利口酒|Cherry liqueur
红酒|Red wine
胡椒|Pepper
黄查特酒|Yellow Chartreuse
姜汁啤酒|Ginger beer
姜汁汽水|Ginger ale
金巴利|Campari
金酒|Gin
君度|Cointreau
冷浓缩咖啡|Chilled espresso
热咖啡|Hot coffee
咖啡利口酒|Coffee liqueur
咖啡|Coffee
卡尔瓦多斯|Calvados
卡莎萨|Cachaça
可可利口酒|Crème de cacao
可乐|Cola
苦艾酒|Absinthe
苦精|Bitters
辣椒酱|Hot sauce
蓝橙酒|Blue curaçao
廊酒|Bénédictine
朗姆|Rum
龙舌兰糖浆|Agave syrup
龙舌兰|Tequila
绿薄荷利口酒|Green crème de menthe
绿查特酒|Green Chartreuse
罗勒|Basil
马拉斯奇诺|Maraschino liqueur
蔓越莓汁|Cranberry juice
梅斯卡尔|Mezcal
奶油|Cream
能量饮料|Energy drink
泥煤威士忌|Peated whisky
柠檬皮|Lemon peel
柠檬片|Lemon slice
柠檬汽水|Lemon soda
柠檬汁|Lemon juice
柠檬|Lemon
橙子|Orange
生姜|Ginger
牛奶|Milk
浓缩咖啡|Espresso
佩乔氏苦精|Peychaud's bitters
皮斯科|Pisco
啤酒|Beer
苹果汁|Apple juice
普洛赛克|Prosecco
普罗塞克|Prosecco
起泡酒|Sparkling wine
青柠片|Lime slice
青柠汁|Lime juice
青柠|Lime
肉桂糖浆|Cinnamon syrup
三秒酒|Triple sec
石榴糖浆|Grenadine
水|Water
苏打水|Soda water
苏格兰威士忌|Scotch whisky
苏格兰|Scotch whisky
碎冰|Crushed ice
汤力水|Tonic water
糖|Sugar
糖浆|Simple syrup
桃泥|Peach purée
桃味利口酒|Peach liqueur
甜味美思|Sweet vermouth
味美思|Vermouth
威士忌|Whiskey
伍斯特酱|Worcestershire sauce
西柚汽水|Grapefruit soda
西柚汁|Grapefruit juice
香槟|Champagne
杏仁糖浆|Orgeat
杏子白兰地|Apricot brandy
雪碧|Sprite
盐|Salt
椰浆|Coconut cream
椰子朗姆|Coconut rum
樱桃白兰地|Cherry brandy
紫罗兰利口酒|Crème de violette
没有龙舌兰糖浆可用|Agave syrup alternative:\u0020
毫升|ml
到|–
茶匙|tsp
汤匙|tbsp
吧勺|barspoon
滴|dash
片|leaves / slices
个|pieces
块|pieces
克|g
或| or\u0020
少量|a little
适量|to taste
补满|to top up
漂浮|float
洗杯|glass rinse
按配方|as directed
鸡尾酒杯|Cocktail glass
岩石杯|Rocks glass
酸酒杯|Sour glass
柯林斯杯|Collins glass
大杯或碗|Large glass or bowl
铜杯或高球杯|Copper mug or highball
细长鸡尾酒杯|Tall cocktail glass
香槟杯|Champagne flute
加冰搅拌后滤入冰镇杯|Stir with ice, then strain into a chilled glass.
加冰搅拌后滤入杯中|Stir with ice, then strain into the glass.
前四项加冰摇匀，倒入杯中后补姜汁汽水|Shake the first four ingredients with ice, pour into the glass and top with ginger ale.
杯中加冰直调|Build over ice in the glass.
加冰摇匀后倒入杯中|Shake with ice, then pour into the glass.
杯中加冰轻轻搅匀|Add ice to the glass and stir gently.
加冰充分摇匀后滤入杯中|Shake thoroughly with ice, then strain into the glass.
加冰大力摇匀后滤入杯中|Shake vigorously with ice, then strain into the glass.
热咖啡中加入酒液后轻轻搅匀|Add the spirits to hot coffee and stir gently.
加冰摇匀后滤入杯中|Shake with ice, then strain into the glass.
前四项加冰摇匀，入杯后补苏打水|Shake the first four ingredients with ice, pour into the glass and top with soda water.
杯中加冰直调，最后补苏打水|Build over ice in the glass, then top with soda water.
杯中加冰直调，青柠片装饰|Build over ice in the glass and garnish with a lime slice.
前四项加冰摇匀，倒入杯中后补苏打水|Shake the first four ingredients with ice, pour into the glass and top with soda water.
杯中加冰直调，最后补姜汁汽水|Build over ice in the glass, then top with ginger ale.
冰镇后直接调和|Chill the ingredients, then mix directly.
杯中加冰直调，最后补雪碧|Build over ice in the glass, then top with Sprite.
热饮搅匀，冷饮可加冰摇匀|Stir for a hot drink; for a cold version, shake with ice.
前六项加冰摇匀，倒入杯中后补可乐|Shake the first six ingredients with ice, pour into the glass and top with cola.
前七项加冰摇匀，倒入杯中后补可乐|Shake the first seven ingredients with ice, pour into the glass and top with cola.
前六项加冰摇匀，倒入杯中后补蔓越莓汁|Shake the first six ingredients with ice, pour into the glass and top with cranberry juice.
前六项加冰摇匀，倒入杯中后补雪碧|Shake the first six ingredients with ice, pour into the glass and top with Sprite.
杯中加冰直调，最后补能量饮料|Build over ice in the glass, then top with energy drink.
前七项加冰摇匀，倒入杯中后补啤酒或雪碧|Shake the first seven ingredients with ice, pour into the glass and top with beer or Sprite.
加冰摇匀后倒入大杯|Shake with ice, then pour into a large glass.
杯中加冰直调，柠檬或青柠装饰|Build over ice in the glass and garnish with lemon or lime.
薄荷与酸甜料轻压，加冰后入朗姆并补苏打水|Gently muddle the mint with the sweet and sour ingredients. Add ice and rum, then top with soda water.
加冰摇匀后滤入冰镇杯|Shake with ice, then strain into a chilled glass.
杯中加冰直调，最后补西柚汽水|Build over ice in the glass, then top with grapefruit soda.
杯中搅拌，加入大冰块|Stir in the glass and add a large ice cube.
加冰直调。|Build over ice.
加冰摇匀，盐边杯。|Shake with ice and serve in a salt-rimmed glass.
加冰摇匀。|Shake with ice.
杯中轻压薄荷后加冰直调。|Gently muddle mint in the glass, then build over ice.
加冰摇匀，过滤入杯。|Shake with ice, then strain into the glass.
与冰块一起搅打后倒入杯中。|Blend with ice, then pour into the glass.
加冰搅拌，过滤入冰镇杯，以橄榄或柠檬皮装饰。|Stir with ice, strain into a chilled glass and garnish with an olive or lemon peel.
加冰搅拌或摇匀，过滤入冰镇杯。|Stir or shake with ice, then strain into a chilled glass.
加冰摇匀或搅拌，过滤入冰镇杯。|Shake or stir with ice, then strain into a chilled glass.
加冰搅拌。|Stir with ice.
高球杯加冰直调。|Build over ice in a highball glass.
前三项加冰摇匀，倒入杯中后加苏打水。|Shake the first three ingredients with ice, pour into the glass and add soda water.
充分摇匀后加苏打水。|Shake thoroughly, then add soda water.
先干摇，再加冰摇匀。|Dry shake first, then shake with ice.
碎冰杯中制作，黑莓利口酒最后淋入。|Build over crushed ice, then drizzle blackberry liqueur over the top.
铜杯或高球杯加冰直调。|Build over ice in a copper mug or highball glass.
加冰摇匀，过滤入马天尼杯。|Shake with ice, then strain into a martini glass.
杯中加冰直调。|Build over ice in the glass.
杯中搅拌。|Stir in the glass.
加冰搅拌，过滤入杯。|Stir with ice, then strain into the glass.
杯中轻压薄荷后加入碎冰和波本搅拌。|Gently muddle mint in the glass, then add crushed ice and bourbon and stir.
摇匀后漂浮泥煤威士忌。|Shake, then float peated whisky on top.
前三项摇匀后加入红酒。|Shake the first three ingredients, then add red wine.
搅拌后倒入洗杯。|Stir, then pour into the rinsed glass.
热饮制作。|Prepare as a hot drink.
加冰直调，石榴糖浆最后慢慢倒入。|Build over ice, then slowly add grenadine last.
轻轻搅匀。|Stir gently.
前三项摇匀后加香槟。|Shake the first three ingredients, then add Champagne.
加冰摇匀，糖边杯可选。|Shake with ice. A sugar rim is optional.
先干摇，再加冰摇。|Dry shake first, then shake with ice.
压碎后加碎冰搅拌。|Muddle, then add crushed ice and stir.
材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。不需装饰。|Shake the ingredients with ice, then strain into a chilled cocktail glass. No garnish.
材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。在表面挤出柠檬皮油。|Shake the ingredients with ice, then strain into a chilled cocktail glass. Express lemon peel oil over the surface.
材料与冰块加入摇壶，短暂摇匀后过滤入预冷的鸡尾酒杯。可用薄荷叶装饰。|Shake the ingredients briefly with ice, then strain into a chilled cocktail glass. Mint leaves are an optional garnish.
材料与冰块加入摇壶，摇匀后过滤入预冷的大号鸡尾酒杯。不需装饰。|Shake the ingredients with ice, then strain into a large chilled cocktail glass. No garnish.
材料与冰块加入摇壶，摇匀后过滤入预冷的鸡尾酒杯。用橙皮装饰。|Shake the ingredients with ice, then strain into a chilled cocktail glass. Garnish with orange peel.
材料与冰块加入摇壶，用力摇匀后过滤入预冷的鸡尾酒杯。不需装饰。|Shake the ingredients vigorously with ice, then strain into a chilled cocktail glass. No garnish.
高球杯装满冰，先倒入姜汁啤酒，再将 Goslings 朗姆漂浮在上层。用青柠角或片装饰。|Fill a highball with ice, add ginger beer and float Goslings rum on top. Garnish with a lime wedge or slice.
在高球杯中加冰，加入金巴利和橙汁，轻轻调和，以橙角装饰。|Add ice, Campari and orange juice to a highball. Mix gently and garnish with an orange wedge.
用柠檬或橙润湿杯缘，蘸细砂糖，放入一条卷起的长柑橘皮。将其余材料在调酒杯中加冰搅匀，过滤入准备好的杯子。|Moisten the rim with lemon or orange, dip in fine sugar and curl a long citrus peel inside. Stir the other ingredients with ice in a mixing glass, then strain into the prepared glass.
加冰摇匀，过滤入冰镇鸡尾酒杯。|Shake with ice, then strain into a chilled cocktail glass.
加冰搅拌，过滤入冰镇鸡尾酒杯；以柠檬皮装饰。|Stir with ice, strain into a chilled cocktail glass and garnish with lemon peel.
杯中放方糖并滴上苦精，加入干邑与可选的 Grand Marnier，缓缓倒入冰镇香槟；以橙皮和酒渍樱桃装饰。|Place a sugar cube in the glass and add bitters. Add Cognac and optional Grand Marnier, then slowly pour in chilled Champagne. Garnish with orange peel and a cocktail cherry.
加冰搅拌，过滤入冰镇鸡尾酒杯；以橙皮装饰。|Stir with ice, strain into a chilled cocktail glass and garnish with orange peel.
加冰摇匀，过滤入盛冰的岩石杯；以菠萝角装饰。|Shake with ice, strain into an ice-filled rocks glass and garnish with a pineapple wedge.
先倒入黑醋栗利口酒，再缓缓加入干白葡萄酒。|Pour in crème de cassis, then slowly add dry white wine.
薄荷、朗姆、青柠汁、糖浆与苦精加冰摇匀，过滤入冰镇杯，最后加入起泡酒；以薄荷枝装饰。|Shake mint, rum, lime juice, syrup and bitters with ice. Strain into a chilled glass, add sparkling wine and garnish with a mint sprig.
加冰搅拌，过滤入冰镇鸡尾酒杯；可用薄荷叶装饰。|Stir with ice, then strain into a chilled cocktail glass. Mint leaves are an optional garnish.
加冰搅拌，过滤入冰镇鸡尾酒杯；以橙皮和酒渍樱桃装饰。|Stir with ice, strain into a chilled cocktail glass and garnish with orange peel and a cocktail cherry.
偏烈、干净，适合慢慢啜饮。|Strong and clean; best sipped slowly.
酒感直接，适合小份量饮用。|Spirit-forward; serve in small portions.
酒款较多，建议按高球杯容量控制补满量。|This uses several spirits. Adjust the top-up to your highball's capacity.
加入蛋白时可先干摇，再加冰摇。|If using egg white, dry shake first, then shake with ice.
IBA 指定 Goslings 朗姆；使用其他黑朗姆时是家庭替代版本。|The IBA recipe specifies Goslings rum. Other dark rums make a home adaptation.
来源中的吧勺与 dash 保留原单位；糖边和长柑橘皮另外准备。|Barspoon and dash measures follow the source. Prepare the sugar rim and long citrus peel separately.
原方备注|Recipe note
在调酒杯中加入冰块。|Add ice to the mixing glass.
冰夹|Ice tongs
量酒器 / 量勺|Jigger / measuring spoon
按原方轻轻搅拌至调和。|Stir gently to combine, following the recipe.
过滤冰块，将酒液倒入最终酒杯。|Strain out the ice and pour into the serving glass.
滤冰器|Strainer
在摇壶中加入冰块。|Add ice to the shaker.
盖紧摇壶，加冰摇匀。|Close the shaker firmly and shake with ice.
将调好的酒液倒入最终酒杯。|Pour the mixed drink into the serving glass.
摇匀并入杯后，再缓缓加入这项材料；不要放进摇壶中摇。|After shaking and pouring into the glass, slowly add this ingredient. Do not shake it in the shaker.
在最终酒杯中加入冰块。|Add ice to the serving glass.
本次演示热饮版本；原方：|This guide shows the hot version. Original method:\u0020
耐热杯|Heatproof glass
装饰夹|Garnish tongs
轻压薄荷与酸甜料，释放香气。|Gently muddle mint with the sweet and sour ingredients to release its aroma.
捣棒|Muddler
最后用苏打水补满。|Top with soda water last.
可选：预先准备盐边杯。|Optional: prepare a salt-rimmed glass.
按原配方先准备盐边杯。|Prepare a salt-rimmed glass as directed.
盐碟|Salt dish
将龙舌兰量入摇壶。|Measure the tequila into the shaker.
量酒器|Jigger
加入橙味利口酒。|Add the orange liqueur.
加入青柠汁。|Add lime juice.
向摇壶中加入冰块。|Add ice to the shaker.
盖紧摇壶，充分摇匀。|Close the shaker firmly and shake thoroughly.
过滤冰块，倒入准备好的酒杯。|Strain out the ice into the prepared glass.
将青柠汁量入最终酒杯。|Measure lime juice into the serving glass.
加入糖浆。|Add syrup.
加入薄荷，轻压释放香气，不要捣碎。|Add mint and press gently to release its aroma without crushing it.
在酒杯中加入冰块。|Add ice to the glass.
量入白朗姆。|Measure in white rum.
用苏打水补满，轻轻搅匀。|Top with soda water and stir gently.
苏打水瓶|Soda water bottle
将白朗姆量入摇壶。|Measure white rum into the shaker.
盖紧并摇匀。|Close firmly and shake.
过滤后倒入冰镇酒杯。|Strain into a chilled glass.
将白朗姆量入搅拌机。|Measure white rum into the blender.
加入椰浆。|Add coconut cream.
加入菠萝汁。|Add pineapple juice.
加入冰块。|Add ice.
盖好杯盖，与冰块一起搅打。|Secure the lid and blend with ice.
量入金酒。|Measure in gin.
缓缓加入汤力水。|Slowly add tonic water.
轻轻调和，保留气泡。|Mix gently to preserve the bubbles.
以柠檬片或青柠片装饰。|Garnish with a lemon or lime slice.
水果夹|Fruit tongs
在调酒杯中加入冰块，另备冰镇的最终酒杯。|Add ice to the mixing glass and prepare a chilled serving glass.
量入干味美思，不能用甜味美思替代。|Measure in dry vermouth. Do not substitute sweet vermouth.
搅拌至酒液充分冷却。|Stir until well chilled.
过滤冰块，将酒液倒入冰镇酒杯。|Strain out the ice into a chilled glass.
按原配方以橄榄或柠檬皮装饰。|Garnish with an olive or lemon peel as directed.
在酒杯中放入冰块。|Place ice in the glass.
量入金巴利。|Measure in Campari.
量入甜味美思。|Measure in sweet vermouth.
加冰搅拌至冷却。|Stir with ice until chilled.
先不加冰，盖紧摇壶干摇；可选蛋白未使用时可跳过此步。|Dry shake without ice first. Skip this step if you are not using the optional egg white.
最后将黑莓利口酒淋入杯中。|Drizzle blackberry liqueur into the glass last.
将伏特加量入摇壶。|Measure vodka into the shaker.
加入咖啡利口酒。|Add coffee liqueur.
加入已冷却的浓缩咖啡。|Add chilled espresso.
充分摇匀。|Shake thoroughly.
过滤入杯。|Strain into the glass.
将糖、苦精和水压碎调和。|Muddle the sugar, bitters and water together.
向调酒杯中加入冰块。|Add ice to the mixing glass.
选择黑麦或波本，量入调酒杯。|Choose rye whiskey or bourbon and measure it into the mixing glass.
加入甜味美思。|Add sweet vermouth.
滴入苦精。|Add the bitters.
苦精瓶|Bitters bottle
搅拌至酒液冷却。|Stir until chilled.
过滤后倒入最终酒杯。|Strain into the serving glass.
最后沿勺背缓缓加入，形成表面漂浮层。|Slowly pour over the back of a spoon last to float a layer on top.
以苦艾酒润洗最终酒杯，倒掉多余酒液。|Rinse the serving glass with absinthe and discard the excess.
将方糖放入调酒杯。|Place the sugar cube in the mixing glass.
加入苦精，将糖压碎调和。|Add bitters and muddle the sugar to combine.
将热咖啡倒入耐热杯，搅拌溶解糖。|Pour hot coffee into a heatproof glass and stir to dissolve the sugar.
沿勺背缓缓加入奶油，使其漂浮在表面。|Slowly pour cream over the back of a spoon so it floats on top.
量入龙舌兰。|Measure in tequila.
加入橙汁，轻轻调和。|Add orange juice and mix gently.
最后缓缓倒入石榴糖浆，让它沉到杯底。|Slowly pour in grenadine last, letting it sink to the bottom.
向最终酒杯加入冰块。|Add ice to the serving glass.
加入阿佩罗。|Add Aperol.
缓缓加入普洛赛克。|Slowly add Prosecco.
加入苏打水。|Add soda water.
轻轻搅匀，保留气泡。|Stir gently to preserve the bubbles.
将金酒量入摇壶。|Measure gin into the shaker.
加入柠檬汁。|Add lemon juice.
摇匀前三项；香槟留到最后。|Shake the first three ingredients. Keep the Champagne for last.
用香槟缓缓补满。|Slowly top with Champagne.
香槟瓶|Champagne bottle
原方可选：预先准备糖边杯。|Optional in the original recipe: prepare a sugar-rimmed glass.
糖碟|Sugar dish
压碎青柠与糖，释放汁液。|Muddle lime with sugar to release the juice.
冰铲|Ice scoop
摇匀至充分冷却。|Shake until well chilled.
过滤到预冷的酒杯中。|Strain into a chilled glass.
在表面挤出柠檬皮油。|Express lemon peel oil over the surface.
短暂摇匀即可。|Shake briefly.
可用薄荷叶装饰。|Mint leaves are an optional garnish.
用橙皮装饰。|Garnish with orange peel.
用力摇匀，让罗勒释放香气。|Shake vigorously to release the basil aroma.
高球杯装满冰块。|Fill a highball glass with ice.
先倒入姜汁啤酒，保留气泡。|Pour in ginger beer first, preserving its bubbles.
沿吧勺背缓慢加入 Goslings 朗姆，让深色酒液浮在上层。|Slowly pour Goslings rum over the back of a barspoon to float it on top.
用青柠角或片装饰。|Garnish with a lime wedge or slice.
高球杯加入冰块。|Add ice to the highball glass.
量取金巴利。|Measure the Campari.
倒入橙汁。|Pour in orange juice.
轻轻调和。|Mix gently.
以橙角装饰。|Garnish with an orange wedge.
准备糖边，并将长橙皮或柠檬皮卷在杯内。|Prepare a sugar rim and curl a long orange or lemon peel inside the glass.
量取白兰地加入调酒杯。|Measure brandy into the mixing glass.
量取马拉斯奇诺加入调酒杯。|Measure maraschino liqueur into the mixing glass.
量取橙味利口酒加入调酒杯。|Measure orange liqueur into the mixing glass.
量取柠檬汁加入调酒杯。|Measure lemon juice into the mixing glass.
量取糖浆加入调酒杯。|Measure syrup into the mixing glass.
量取苦精加入调酒杯。|Measure bitters into the mixing glass.
充分搅拌冷却。|Stir until well chilled.
过滤到准备好的糖边杯。|Strain into the prepared sugar-rimmed glass.
过滤入冰镇酒杯。|Strain into a chilled glass.
搅拌至充分冷却。|Stir until well chilled.
以柠檬皮装饰。|Garnish with lemon peel.
用橙皮和酒渍樱桃装饰。|Garnish with orange peel and a cocktail cherry.
以橙皮装饰。|Garnish with orange peel.
在岩石杯中加入冰块。|Add ice to the rocks glass.
过滤入盛冰的岩石杯。|Strain into an ice-filled rocks glass.
以菠萝角装饰。|Garnish with a pineapple wedge.
过滤入冰镇杯。|Strain into a chilled glass.
以薄荷枝装饰。|Garnish with a mint sprig.
以橙皮和酒渍樱桃装饰。|Garnish with orange peel and a cocktail cherry.
量取并加入|Measure and add\u0020
加入|Add\u0020
普通糖浆|Simple syrup
盐边杯可选|Salt rim (optional)
盐边可选|Salt rim (optional)
深色朗姆|Dark rum
葡萄柚汁|Grapefruit juice
青柠 1 个切块|1 lime, cut into wedges
白糖|White sugar
`.trim().split('\n').map(line => { const i=line.indexOf('|'); return [line.slice(0,i),line.slice(i+1)]; })));

globalThis.BarData = require("./data");
(() => {
  const { html: localHTML, t: localText } = globalThis.BarI18n || { html: s => s, t: s => s };
  const WIDTH = 1080, MAX_HEIGHT = 8192;
  const sans = '"PingFang SC", "Microsoft YaHei", sans-serif';
  const templates = [
    { id: 'theme', name: '跟随主题', subtitle: '与当前应用外观一致' },
    { id: 'archive', name: '奶油吧台', subtitle: '奶油白 · 珊瑚橙', paper: '#f2e9d8', ink: '#31535a', accent: '#cf795e', soft: '#ead9b9', panel: '#fffaf0', motif: 'tabs' },
    { id: 'botanical', name: '青柠气泡', subtitle: '鼠尾草绿 · 青柠黄', paper: '#dbe6d2', ink: '#31535a', accent: '#a4b776', soft: '#c4d5b4', panel: '#f6f9ed', motif: 'bubbles' },
    { id: 'tropical', name: '落日橘调', subtitle: '杏桃橘 · 暖沙色', paper: '#f1d4bc', ink: '#31535a', accent: '#db9262', soft: '#edb393', panel: '#fff5e6', motif: 'sun' },
    { id: 'ocean', name: '午夜海蓝', subtitle: '深海蓝 · 冰川青', paper: '#132b39', ink: '#e3f0ee', accent: '#80c9c3', soft: '#264957', panel: '#1d3946', motif: 'waves', dark: true },
    { id: 'berry', name: '莓果奶昔', subtitle: '浅莓粉 · 玫瑰红', paper: '#f0dbe0', ink: '#633d4c', accent: '#c27690', soft: '#e9c1cd', panel: '#fff3f5', motif: 'diamonds' },
    { id: 'violet', name: '雾紫微醺', subtitle: '雾紫灰 · 鸢尾紫', paper: '#e6e0ef', ink: '#49465f', accent: '#a193c6', soft: '#d6cce6', panel: '#f7f4fc', motif: 'bubbles' },
    { id: 'cocoa', name: '可可拿铁', subtitle: '燕麦米 · 可可棕', paper: '#e5dacb', ink: '#54463d', accent: '#b38b67', soft: '#d1bba2', panel: '#f8f0e5', motif: 'tabs' },
  ];
  function resolveTemplate(id, theme = 'bar') {
    let t = templates.find(t => t.id === id) || templates[0];
    if (t.id === 'theme') {
      t = theme === 'light'
        ? { ...t, paper: '#f2ecdf', ink: '#293d32', accent: '#976442', soft: '#e5e5d3', panel: '#fff9ee', motif: 'tabs' }
        : { ...t, paper: theme === 'dark' ? '#0b100e' : '#0e1714', ink: '#f0e7d6', accent: '#d9b579', soft: theme === 'dark' ? '#19291f' : '#21372d', panel: theme === 'dark' ? '#131c17' : '#19251f', motif: 'diamonds', dark: true };
    }
    return { ...t, edge: t.dark ? t.accent : t.ink, tasteBg: t.dark ? t.soft : t.ink, tasteInk: t.dark ? t.ink : t.panel };
  }
  function dataFor(recipe) {
    const profile = BarTaste.profile(recipe);
    const mainParts = (recipe.parts || recipe.ingredients.map(BarCore.ingredient)).filter(p => !p.optional && !p.substitution);
    const known = mainParts.length > 0 && !profile.unknown.length;
    const bases = [...new Set(mainParts
      .flatMap(p => p.types.map(type => BarTasteData[BarCore.canonical(type)]?.base).filter(Boolean)))];
    return {
      name: globalThis.BarI18n?.name(recipe) || recipe.chineseName, english: globalThis.BarI18n?.locale === 'en' ? '' : recipe.englishName || '',
      ingredients: recipe.ingredients.map(value => recipe.isUserCreated ? value : localText(value)), glass: localText(recipe.glass || ''),
      base: localText(bases.join(' / ') || (known ? '无基酒' : '基酒待补充')),
      family: known ? localText(profile.family) : '', known,
      tags: known ? BarTaste.characteristics(profile.vector).map(localText) : [],
      vector: known ? [...profile.vector] : null,
      source: recipe.source?.title || '', art: BarArt.drink(recipe),
    };
  }
  // Preserve every character, including explicit newlines and quantities. The caller
  // supplies real font metrics in browsers and a deterministic measure in tests.
  function wrap(text, width, measure) {
    const lines = [];
    for (const paragraph of String(text).split('\n')) {
      let line = '';
      for (const char of Array.from(paragraph)) {
        if (line && measure(line + char) > width) {
        const space = line.lastIndexOf(' ');
        if (space > 0 && /[A-Za-z0-9]/.test(char) && /[A-Za-z0-9]$/.test(line)) { lines.push(line.slice(0, space + 1)); line = line.slice(space + 1); }
        else { lines.push(line); line = ''; }
      }
        line += char;
      }
      lines.push(line);
    }
    return lines;
  }
  function layout(data, measure) {
    const blocks = [];
    const add = (text, x, y, width, size, lineHeight, kind = 'body', align = 'left', role = '') => {
      const lines = wrap(text, width, s => measure(s, size, kind));
      blocks.push({ lines, x, y, width, size, lineHeight, kind, align, role });
      return y + (lines.length - 1) * lineHeight;
    };
    let y = add(data.name, 82, 192, 565, 66, 82, 'title');
    if (data.english) y = add(data.english, 84, y + 48, 555, 29, 39, 'english');
    y = add(data.base, 84, y + 55, 545, 27, 38, 'muted');
    if (data.family) y = add(data.family, 84, y + 40, 545, 27, 38, 'muted');
    const glassEnd = data.glass ? add(data.glass, 845, 398, 260, 24, 32, 'muted', 'center') : 398;
    const mainY = Math.max(430, y + 42, glassEnd + 32);
    let ingredientY = mainY + 118;
    const rows = [];
    for (const ingredient of data.ingredients) {
      const top = ingredientY;
      ingredientY = add(ingredient, 140, ingredientY, 824, 34, 46, 'body', 'left', 'ingredient');
      rows.push({ top, bottom: ingredientY + 22 });
      ingredientY += 65;
    }
    const divider = ingredientY - 18;
    const footer = divider + 24;
    const sourceLines = data.source ? wrap(localText(`配方来源 · ${data.source}`), 910, s => measure(s, 21, 'muted')) : [];
    const height = Math.max(1080, footer + 238 + Math.max(1, sourceLines.length) * 29 + 55);
    if (height > MAX_HEIGHT) throw new Error('配方文字过长，无法放入一张清晰的图片。请精简后重试。');
    return { width: WIDTH, height, blocks, rows, mainY, divider, footer, sourceLines };
  }
  function font(size, kind) {
    return `${kind === 'title' ? '700' : kind === 'english' ? '500' : '400'} ${size}px ${sans}`;
  }
  function line(ctx, x1, y1, x2, y2) {
    ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
  }
  function box(ctx, x, y, width, height, radius, fill, stroke = null, lineWidth = 3) {
    const r = Math.min(radius, width / 2, height / 2);
    ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + width, y, x + width, y + height, r);
    ctx.arcTo(x + width, y + height, x, y + height, r); ctx.arcTo(x, y + height, x, y, r);
    ctx.arcTo(x, y, x + width, y, r); ctx.closePath();
    if (fill) { ctx.fillStyle = fill; ctx.fill(); }
    if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lineWidth; ctx.stroke(); }
  }
  function circle(ctx, x, y, radius, fill, stroke = null) {
    ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2);
    if (fill) { ctx.fillStyle = fill; ctx.fill(); }
    if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 3; ctx.stroke(); }
  }
  function border(ctx, template, height) {
    ctx.fillStyle = template.paper; ctx.fillRect(0, 0, WIDTH, height);
    box(ctx, 23, 23, WIDTH - 46, height - 46, 38, null, template.edge, 4);
    ctx.globalAlpha = .3;
    box(ctx, 36, 36, WIDTH - 72, height - 72, 29, null, template.edge, 1.4);
    ctx.globalAlpha = 1;
    for (const x of [51, WIDTH - 51]) {
      for (const y of [51, height - 51]) circle(ctx, x, y, 4, template.accent);
    }
    ctx.strokeStyle = template.accent; ctx.lineWidth = 2; ctx.lineCap = 'round';
    for (const x of [23, WIDTH - 23]) {
      for (let i = -2; i <= 2; i++) line(ctx, x - 5, height / 2 + i * 12, x + 5, height / 2 + i * 12);
    }
    if (template.motif === 'bubbles') {
      for (const y of [58, 84, 110]) circle(ctx, 23, y + 37, 7, template.accent, template.ink);
      for (const y of [58, 84, 110]) circle(ctx, WIDTH - 23, height - y - 37, 7, template.accent, template.ink);
    } else if (template.motif === 'waves') {
      for (let i = 0; i < 3; i++) {
        const y = 95 + i * 18;
        ctx.beginPath(); ctx.moveTo(14, y); ctx.quadraticCurveTo(23, y - 13, 32, y); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(WIDTH - 32, height - y); ctx.quadraticCurveTo(WIDTH - 23, height - y - 13, WIDTH - 14, height - y); ctx.stroke();
      }
    } else if (template.motif === 'diamonds') {
      for (const [x, y] of [[23, 113], [WIDTH - 23, height - 113]]) {
        ctx.save(); ctx.translate(x, y); ctx.rotate(Math.PI / 4);
        box(ctx, -10, -10, 20, 20, 4, template.accent, template.edge, 2); ctx.restore();
        circle(ctx, x, y - 29, 4, template.accent); circle(ctx, x, y + 29, 4, template.accent);
      }
    } else if (template.motif === 'sun') {
      box(ctx, 94, 16, 156, 14, 7, template.accent, template.ink, 3);
      box(ctx, WIDTH - 250, height - 30, 156, 14, 7, template.accent, template.ink, 3);
    } else {
      box(ctx, 13, 86, 20, 86, 8, template.accent, template.ink, 3);
      box(ctx, WIDTH - 33, height - 172, 20, 86, 8, template.accent, template.ink, 3);
    }
  }
  function text(ctx, value, x, y, size, color, align = 'left', kind = 'body') {
    ctx.font = font(size, kind); ctx.fillStyle = color; ctx.textAlign = align; ctx.fillText(value, x, y);
  }
  function draw(ctx, data, template, plan, art) {
    const { height, mainY, divider, footer } = plan;
    border(ctx, template, height);
    box(ctx, 78, 58, 40, 40, 12, template.ink);
    ctx.strokeStyle = template.panel; ctx.lineWidth = 2.8;
    ctx.beginPath(); ctx.moveTo(87, 69); ctx.lineTo(109, 69); ctx.lineTo(98, 81); ctx.closePath(); ctx.stroke();
    line(ctx, 98, 81, 98, 90); line(ctx, 92, 90, 104, 90);
    circle(ctx, 108, 69, 4, template.accent);
    text(ctx, localText('大喝特喝'), 134, 87, 27, template.ink, 'left', 'title');
    text(ctx, 'COCKTAIL RECIPE', 997, 84, 20, template.ink, 'right', 'english');
    box(ctx, 690, 122, 310, 246, 46, template.soft);
    if (template.motif === 'sun') circle(ctx, 925, 180, 37, template.accent);
    else if (template.motif === 'bubbles') { circle(ctx, 974, 146, 10, template.panel); circle(ctx, 714, 344, 7, template.panel); }
    else { box(ctx, 713, 141, 56, 14, 7, template.accent); box(ctx, 939, 330, 38, 14, 7, template.accent); }
    art(ctx, 732, 109, 234, 278);
    box(ctx, 60, mainY, 960, divider - mainY, 28, template.panel, template.edge, 3);
    text(ctx, localText('配方'), 98, mainY + 57, 32, template.ink, 'left', 'title');
    text(ctx, localText(`${data.ingredients.length} 项材料`), 978, mainY + 55, 24, template.ink, 'right');
    ctx.strokeStyle = template.soft; ctx.lineWidth = 2;
    line(ctx, 98, mainY + 77, 981, mainY + 77);
    plan.rows.forEach((row, i) => {
      circle(ctx, 110, row.top - 12, 6, template.accent);
      if (i < plan.rows.length - 1) line(ctx, 140, row.bottom, 979, row.bottom);
    });
    for (const b of plan.blocks) {
      const parts = b.role === 'ingredient' && b.lines.length === 1
        ? b.lines[0].match(/^(.+?)\s+(\d+(?:[./–—-]\d+)?\s*(?:ml|cl|滴|dash|片|个|茶匙|吧勺|毫升|克|g))$/i) : null;
      ctx.font = font(b.size, b.kind);
      if (parts && ctx.measureText(parts[1]).width + ctx.measureText(parts[2]).width + 45 < b.width) {
        text(ctx, parts[1], b.x, b.y, b.size, template.ink);
        text(ctx, parts[2], b.x + b.width, b.y, b.size, template.ink, 'right', 'english');
        continue;
      }
      b.lines.forEach((s, i) => text(ctx, s, b.x, b.y + i * b.lineHeight, b.size, template.ink, b.align, b.kind));
    }
    box(ctx, 60, footer, 960, 238, 28, template.tasteBg);
    const tags = !data.known ? localText('风味待补充') : data.tags.join(' · ') || localText('轻盈 · 柔和');
    text(ctx, localText('风味'), 99, footer + 57, 28, template.tasteInk, 'left', 'title');
    text(ctx, tags, 978, footer + 57, 27, template.tasteInk, 'right');
    if (data.known) {
      [0, 1, 3].forEach((index, column) => {
        const x = 99 + column * 309;
        text(ctx, localText(BarTaste.dimensions[index]), x, footer + 131, 27, template.tasteInk);
        box(ctx, x, footer + 158, 264, 16, 8, '#ffffff28');
        if (data.vector[index]) box(ctx, x, footer + 158, 264 * data.vector[index] / 100, 16, 8, template.accent);
      });
    } else text(ctx, localText('部分材料尚无风味数据'), 99, footer + 137, 27, template.tasteInk);
    plan.sourceLines.forEach((s, i) => text(ctx, s, 84, height - 48 - (plan.sourceLines.length - 1 - i) * 29, 21, template.ink));
    if (!plan.sourceLines.length) text(ctx, localText('大喝特喝  /  MY LITTLE HOME BAR'), 84, height - 48, 20, template.ink);
  }

 globalThis.BarShare = {templates, resolveTemplate, dataFor, wrap, layout, font, draw};
})();

const originalShareData = globalThis.BarShare.dataFor;
globalThis.BarShare.dataFor = recipe => {
  const result = originalShareData(recipe);
  if (BarI18n.locale === 'en' && !recipe.isUserCreated) result.ingredients = result.ingredients.map(s => s.replace(/([a-z])to top up/gi, '$1, to top up').replace(/([a-z])(?=[0-9])/gi, '$1 '));
  return result;
};
  function contentsAt(steps, index, target) {
    const containers = {};
    let source = "shaker";
    for (const step of steps.slice(0, index + 1)) {
      const content = containers[step.target] ||= { level: 0, ice: false };
      if (["shaker", "mixing", "blender"].includes(step.target)) source = step.target;
      if (step.action === "ice") content.ice = true;
      if (step.action === "blend") content.ice = false;
      if (step.action === "pour") content.level = Math.min(0.7, content.level + 0.18);
      if (step.action === "top" || step.action === "float") content.level = 0.78;
      if (step.action === "strain" || step.action === "serve") {
        content.level = 0.65;
        if (step.action === "serve") content.ice ||= containers[step.source || source]?.ice || false;
      }
    }
    return containers[target] || { level: 0, ice: false };
  }
  function visualAt(visual, steps, index, target, complete = false) {
    const result = { ...visual };
    if (target !== 'glass' || (!complete && visual.layerPart && !steps.slice(0,index+1).some(s =>
      ['pour','float','top'].includes(s.action) && s.ingredient?.raw.includes(visual.layerPart)))) delete result.layers;
    if (!complete && !steps.slice(0,index+1).some(s => s.action === 'shake')) result.foam = false;
    return result;
  }

module.exports = { core: BarCore, taste: BarTaste, i18n: BarI18n, art: BarArt, share: globalThis.BarShare, contentsAt, visualAt, tasteData: BarTasteData };
