// Generated by scripts/export-weapp-audio.mjs.
// 小程序没有 wx.loadSubpackage（那是小游戏 API），用分包异步化 require.async 下载语音分包。
// 路径必须是字面量，开发者工具才能在编译时识别。
module.exports = {
  'voice-01': () => require.async('../voice-01/pack.js'),
  'voice-02': () => require.async('../voice-02/pack.js'),
  'voice-03': () => require.async('../voice-03/pack.js'),
  'voice-04': () => require.async('../voice-04/pack.js'),
  'voice-05': () => require.async('../voice-05/pack.js'),
  'voice-06': () => require.async('../voice-06/pack.js'),
};
