import { mkdirSync, writeFileSync, cpSync, readFileSync } from "node:fs";
import { readRecipes } from "./export-recipes.mjs";
import { compileProcedure } from "../data/procedures.mjs";
import { researchedRecipes } from "../data/researched-recipes.mjs";
import { syncCuratedSwift } from './sync-curated-swift.mjs';
import { appearanceFor } from "../data/drink-appearance.mjs";
import "../Cocktail60/BarWeb/core.js";
const { ingredient, canonical, category } = globalThis.BarCore;
syncCuratedSwift();
const recipes = [...readRecipes(), ...researchedRecipes].map((r) => ({
  ...r,
  appearance: appearanceFor(r),
  parts: r.ingredients.map(ingredient),
}));
const names = new Set(recipes.flatMap((r) => r.parts.flatMap((p) => p.types)));
["椰子朗姆", "君度", "三秒酒", "甜味美思", "干味美思"].forEach((n) =>
  names.add(n),
);
const catalog = [...names]
  .map(canonical)
  .sort((a, b) => a.localeCompare(b, "zh"))
  .map((name) => ({ name, category: category(name) }));
const tutorials = JSON.parse(
  readFileSync(new URL("../data/tutorials.json", import.meta.url), "utf8"),
);
for (const id of Object.keys(tutorials)) {
  if (!recipes.some((r) => r.id === id))
    throw new Error(`Unknown tutorial recipe ${id}`);
}
for (const recipe of recipes) {
  const steps = recipe.steps || tutorials[recipe.id] || compileProcedure(recipe);
  recipe.steps = steps.map((step) => {
    if (step.part !== undefined && !recipe.parts[step.part])
      throw new Error(`Invalid ingredient in ${recipe.id}`);
    return {
      ...step,
      ingredient: step.part === undefined ? null : recipe.parts[step.part],
    };
  });
}
const output = new URL("../Cocktail60/BarWeb/data.js", import.meta.url);
writeFileSync(
  output,
  `// Generated by npm run build from Swift recipes and data/*.mjs / tutorials.json.\nglobalThis.BarData = ${JSON.stringify({ recipes, catalog }, null, 2)};\n`,
);
mkdirSync(new URL("../dist/", import.meta.url), { recursive: true });
cpSync(
  new URL("../Cocktail60/BarWeb/", import.meta.url),
  new URL("../dist/", import.meta.url),
  { recursive: true },
);
console.log(
  `Built ${recipes.length} recipes with step-by-step procedures and ${catalog.length} ingredient types.`,
);
