// Native WeChat package. No cloud, npm runtime dependencies, or WebView required.
import './build.mjs';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import '../Cocktail60/BarWeb/taste-data.js';
import '../Cocktail60/BarWeb/taste.js';
import '../Cocktail60/BarWeb/data.js';
const out = new URL('../wechat/shared/', import.meta.url);
mkdirSync(out, { recursive: true });
let engine = '// Generated by npm run build:weapp; edit the shared BarWeb source instead.\nconst globalThis = {};\nlet BarCore, BarTasteData, BarTaste, BarI18n, BarArt;\nconst hasOwn = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);\n';
for (const [file, symbol] of [['core.js', 'BarCore'], ['taste-data.js', 'BarTasteData'], ['taste.js', 'BarTaste'], ['i18n.js','BarI18n'], ['art.js','BarArt']]) {
  engine += readFileSync(new URL(`../Cocktail60/BarWeb/${file}`, import.meta.url), 'utf8').replaceAll('Object.hasOwn(', 'hasOwn(');
  engine += `\n${symbol} = globalThis.${symbol};\n`;
}
for (const file of ['i18n-en.js','i18n-recipes-en.js']) engine += '\n' + readFileSync(new URL(`../Cocktail60/BarWeb/${file}`, import.meta.url), 'utf8');
engine += '\nglobalThis.BarData = require("./data");\n';
// Keep the original share-card layout and painter; replace only browser export.
let share = readFileSync(new URL('../Cocktail60/BarWeb/share-card.js', import.meta.url), 'utf8');
share = share.slice(0, share.indexOf('  function loadArt(')) + '\n globalThis.BarShare = {templates, resolveTemplate, dataFor, wrap, layout, font, draw};\n})();\n';
share = share.replace('ctx.drawImage(art, 732, 109, 234, 278);','art(ctx, 732, 109, 234, 278);');
share = share.replace('if (line && measure(line + char) > width) { lines.push(line); line = \'\'; }', `if (line && measure(line + char) > width) {
        const space = line.lastIndexOf(' ');
        if (space > 0 && /[A-Za-z0-9]/.test(char) && /[A-Za-z0-9]$/.test(line)) { lines.push(line.slice(0, space + 1)); line = line.slice(space + 1); }
        else { lines.push(line); line = ''; }
      }`);
engine += share;
engine += `\nconst originalShareData = globalThis.BarShare.dataFor;
globalThis.BarShare.dataFor = recipe => {
  const result = originalShareData(recipe);
  if (BarI18n.locale === 'en' && !recipe.isUserCreated) result.ingredients = result.ingredients.map(s => s.replace(/([a-z])to top up/gi, '$1, to top up').replace(/([a-z])(?=[0-9])/gi, '$1 '));
  return result;
};\n`;
const player = readFileSync(new URL('../Cocktail60/BarWeb/player.js', import.meta.url), 'utf8');
engine += player.slice(player.indexOf('  function contentsAt('), player.indexOf('  function render()'));
engine += '\nmodule.exports = { core: BarCore, taste: BarTaste, i18n: BarI18n, art: BarArt, share: globalThis.BarShare, contentsAt, visualAt, tasteData: BarTasteData };\n';
writeFileSync(new URL('engine.js', out), engine);
writeFileSync(new URL('data.js', out), '// Generated recipe data.\nmodule.exports = ' + JSON.stringify(globalThis.BarData) + ';\n');
console.log(`WeChat: ${globalThis.BarData.recipes.length} recipes exported to wechat/. Import that folder into WeChat DevTools.`);
await import('./localize-weapp.mjs');
